// <auto-generated>
/* 
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Fingerprint.ServerSdk.Client;

namespace Fingerprint.ServerSdk.Model
{
    /// <summary>
    /// The verification status of the bot's identity:  * `verified` - well-known bot with publicly verifiable identity, directed by the bot provider.  * `signed` - bot that signs its platform via Web Bot Auth, directed by the bot provider's customers.  * `spoofed` - bot that claims a public identity but fails verification.  * `unknown` - bot that does not publish a verifiable identity. 
    /// </summary>
    /// <value>The verification status of the bot's identity:  * `verified` - well-known bot with publicly verifiable identity, directed by the bot provider.  * `signed` - bot that signs its platform via Web Bot Auth, directed by the bot provider's customers.  * `spoofed` - bot that claims a public identity but fails verification.  * `unknown` - bot that does not publish a verifiable identity. </value>
    public enum BotInfoIdentity
    {
        /// <summary>
        /// Enum Verified for value: verified
        /// </summary>
        Verified = 1,

        /// <summary>
        /// Enum Signed for value: signed
        /// </summary>
        Signed = 2,

        /// <summary>
        /// Enum Spoofed for value: spoofed
        /// </summary>
        Spoofed = 3,

        /// <summary>
        /// Enum Unknown for value: unknown
        /// </summary>
        Unknown = 4,

        /// <summary>
        /// Catch-all value used when the API returns an enum value that this version of the SDK does not recognize. Upgrade the SDK to a version that supports the value.
        /// </summary>
        UnsupportedValueSdkUpgradeRequired = -1
    }

    /// <summary>
    /// Converts <see cref="BotInfoIdentity"/> to and from the JSON value
    /// </summary>
    public static class BotInfoIdentityValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="BotInfoIdentity"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static BotInfoIdentity FromString(string value)
        {
            if (value.Equals("verified"))
                return BotInfoIdentity.Verified;

            if (value.Equals("signed"))
                return BotInfoIdentity.Signed;

            if (value.Equals("spoofed"))
                return BotInfoIdentity.Spoofed;

            if (value.Equals("unknown"))
                return BotInfoIdentity.Unknown;

            throw new NotImplementedException($"Could not convert value to type BotInfoIdentity: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="BotInfoIdentity"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static BotInfoIdentity? FromStringOrDefault(string value)
        {
            if (value.Equals("verified"))
                return BotInfoIdentity.Verified;

            if (value.Equals("signed"))
                return BotInfoIdentity.Signed;

            if (value.Equals("spoofed"))
                return BotInfoIdentity.Spoofed;

            if (value.Equals("unknown"))
                return BotInfoIdentity.Unknown;

            return BotInfoIdentity.UnsupportedValueSdkUpgradeRequired;
        }

        /// <summary>
        /// Converts the <see cref="BotInfoIdentity"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(BotInfoIdentity value)
        {
            if (value == BotInfoIdentity.Verified)
                return "verified";

            if (value == BotInfoIdentity.Signed)
                return "signed";

            if (value == BotInfoIdentity.Spoofed)
                return "spoofed";

            if (value == BotInfoIdentity.Unknown)
                return "unknown";

            // Serialize the catch-all value rather than throwing, so models holding an enum value
            // this SDK version does not support can still be re-serialized. The original (unsupported)
            // value is not preserved.
            if (value == BotInfoIdentity.UnsupportedValueSdkUpgradeRequired)
                return "unsupported_value_sdk_upgrade_required";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BotInfoIdentity"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class BotInfoIdentityJsonConverter : JsonConverter<BotInfoIdentity>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override BotInfoIdentity Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            BotInfoIdentity? result = rawValue == null
                ? null
                : BotInfoIdentityValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the BotInfoIdentity to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="botInfoIdentity"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, BotInfoIdentity botInfoIdentity, JsonSerializerOptions options)
        {
            writer.WriteStringValue(BotInfoIdentityValueConverter.ToJsonValue(botInfoIdentity).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BotInfoIdentity"/>
    /// </summary>
    public class BotInfoIdentityNullableJsonConverter : JsonConverter<BotInfoIdentity?>
    {
        /// <summary>
        /// Returns a BotInfoIdentity from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override BotInfoIdentity? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            BotInfoIdentity? result = rawValue == null
                ? null
                : BotInfoIdentityValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the BotInfoIdentity to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="botInfoIdentity"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, BotInfoIdentity? botInfoIdentity, JsonSerializerOptions options)
        {
            writer.WriteStringValue(botInfoIdentity.HasValue ? BotInfoIdentityValueConverter.ToJsonValue(botInfoIdentity.Value).ToString() : "null");
        }
    }
}
