// <auto-generated>
/* 
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Fingerprint.ServerSdk.Client;

namespace Fingerprint.ServerSdk.Model
{
    /// <summary>
    /// Confidence level of the bot identification.
    /// </summary>
    /// <value>Confidence level of the bot identification.</value>
    public enum BotInfoConfidence
    {
        /// <summary>
        /// Enum Low for value: low
        /// </summary>
        Low = 1,

        /// <summary>
        /// Enum Medium for value: medium
        /// </summary>
        Medium = 2,

        /// <summary>
        /// Enum High for value: high
        /// </summary>
        High = 3,

        /// <summary>
        /// Catch-all value used when the API returns an enum value that this version of the SDK does not recognize. Upgrade the SDK to a version that supports the value.
        /// </summary>
        UnsupportedValueSdkUpgradeRequired = -1
    }

    /// <summary>
    /// Converts <see cref="BotInfoConfidence"/> to and from the JSON value
    /// </summary>
    public static class BotInfoConfidenceValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="BotInfoConfidence"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static BotInfoConfidence FromString(string value)
        {
            if (value.Equals("low"))
                return BotInfoConfidence.Low;

            if (value.Equals("medium"))
                return BotInfoConfidence.Medium;

            if (value.Equals("high"))
                return BotInfoConfidence.High;

            throw new NotImplementedException($"Could not convert value to type BotInfoConfidence: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="BotInfoConfidence"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static BotInfoConfidence? FromStringOrDefault(string value)
        {
            if (value.Equals("low"))
                return BotInfoConfidence.Low;

            if (value.Equals("medium"))
                return BotInfoConfidence.Medium;

            if (value.Equals("high"))
                return BotInfoConfidence.High;

            return BotInfoConfidence.UnsupportedValueSdkUpgradeRequired;
        }

        /// <summary>
        /// Converts the <see cref="BotInfoConfidence"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(BotInfoConfidence value)
        {
            if (value == BotInfoConfidence.Low)
                return "low";

            if (value == BotInfoConfidence.Medium)
                return "medium";

            if (value == BotInfoConfidence.High)
                return "high";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BotInfoConfidence"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class BotInfoConfidenceJsonConverter : JsonConverter<BotInfoConfidence>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override BotInfoConfidence Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            BotInfoConfidence? result = rawValue == null
                ? null
                : BotInfoConfidenceValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the BotInfoConfidence to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="botInfoConfidence"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, BotInfoConfidence botInfoConfidence, JsonSerializerOptions options)
        {
            writer.WriteStringValue(BotInfoConfidenceValueConverter.ToJsonValue(botInfoConfidence).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BotInfoConfidence"/>
    /// </summary>
    public class BotInfoConfidenceNullableJsonConverter : JsonConverter<BotInfoConfidence?>
    {
        /// <summary>
        /// Returns a BotInfoConfidence from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override BotInfoConfidence? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            BotInfoConfidence? result = rawValue == null
                ? null
                : BotInfoConfidenceValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the BotInfoConfidence to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="botInfoConfidence"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, BotInfoConfidence? botInfoConfidence, JsonSerializerOptions options)
        {
            writer.WriteStringValue(botInfoConfidence.HasValue ? BotInfoConfidenceValueConverter.ToJsonValue(botInfoConfidence.Value).ToString() : "null");
        }
    }
}
