// <auto-generated>
/* 
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Fingerprint.ServerSdk.Client;

namespace Fingerprint.ServerSdk.Model
{
    /// <summary>
    /// The type and purpose of the bot. 
    /// </summary>
    /// <value>The type and purpose of the bot. </value>
    public enum BotInfoCategory
    {
        /// <summary>
        /// Enum AdvertisingAndMarketing for value: advertising_and_marketing
        /// </summary>
        AdvertisingAndMarketing = 1,

        /// <summary>
        /// Enum Aggregator for value: aggregator
        /// </summary>
        Aggregator = 2,

        /// <summary>
        /// Enum AiAgent for value: ai_agent
        /// </summary>
        AiAgent = 3,

        /// <summary>
        /// Enum AiAssistant for value: ai_assistant
        /// </summary>
        AiAssistant = 4,

        /// <summary>
        /// Enum AiBrowser for value: ai_browser
        /// </summary>
        AiBrowser = 5,

        /// <summary>
        /// Enum AiCrawler for value: ai_crawler
        /// </summary>
        AiCrawler = 6,

        /// <summary>
        /// Enum AiSearch for value: ai_search
        /// </summary>
        AiSearch = 7,

        /// <summary>
        /// Enum BrowserAutomation for value: browser_automation
        /// </summary>
        BrowserAutomation = 8,

        /// <summary>
        /// Enum Ecommerce for value: ecommerce
        /// </summary>
        Ecommerce = 9,

        /// <summary>
        /// Enum MonitoringAndAnalytics for value: monitoring_and_analytics
        /// </summary>
        MonitoringAndAnalytics = 10,

        /// <summary>
        /// Enum Other for value: other
        /// </summary>
        Other = 11,

        /// <summary>
        /// Enum Scraping for value: scraping
        /// </summary>
        Scraping = 12,

        /// <summary>
        /// Enum Security for value: security
        /// </summary>
        Security = 13,

        /// <summary>
        /// Enum SearchEngineCrawler for value: search_engine_crawler
        /// </summary>
        SearchEngineCrawler = 14,

        /// <summary>
        /// Enum SearchEngineOptimization for value: search_engine_optimization
        /// </summary>
        SearchEngineOptimization = 15,

        /// <summary>
        /// Enum Unknown for value: unknown
        /// </summary>
        Unknown = 16,

        /// <summary>
        /// Catch-all value used when the API returns an enum value that this version of the SDK does not recognize. Upgrade the SDK to a version that supports the value.
        /// </summary>
        UnsupportedValueSdkUpgradeRequired = -1
    }

    /// <summary>
    /// Converts <see cref="BotInfoCategory"/> to and from the JSON value
    /// </summary>
    public static class BotInfoCategoryValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="BotInfoCategory"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static BotInfoCategory FromString(string value)
        {
            if (value.Equals("advertising_and_marketing"))
                return BotInfoCategory.AdvertisingAndMarketing;

            if (value.Equals("aggregator"))
                return BotInfoCategory.Aggregator;

            if (value.Equals("ai_agent"))
                return BotInfoCategory.AiAgent;

            if (value.Equals("ai_assistant"))
                return BotInfoCategory.AiAssistant;

            if (value.Equals("ai_browser"))
                return BotInfoCategory.AiBrowser;

            if (value.Equals("ai_crawler"))
                return BotInfoCategory.AiCrawler;

            if (value.Equals("ai_search"))
                return BotInfoCategory.AiSearch;

            if (value.Equals("browser_automation"))
                return BotInfoCategory.BrowserAutomation;

            if (value.Equals("ecommerce"))
                return BotInfoCategory.Ecommerce;

            if (value.Equals("monitoring_and_analytics"))
                return BotInfoCategory.MonitoringAndAnalytics;

            if (value.Equals("other"))
                return BotInfoCategory.Other;

            if (value.Equals("scraping"))
                return BotInfoCategory.Scraping;

            if (value.Equals("security"))
                return BotInfoCategory.Security;

            if (value.Equals("search_engine_crawler"))
                return BotInfoCategory.SearchEngineCrawler;

            if (value.Equals("search_engine_optimization"))
                return BotInfoCategory.SearchEngineOptimization;

            if (value.Equals("unknown"))
                return BotInfoCategory.Unknown;

            throw new NotImplementedException($"Could not convert value to type BotInfoCategory: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="BotInfoCategory"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static BotInfoCategory? FromStringOrDefault(string value)
        {
            if (value.Equals("advertising_and_marketing"))
                return BotInfoCategory.AdvertisingAndMarketing;

            if (value.Equals("aggregator"))
                return BotInfoCategory.Aggregator;

            if (value.Equals("ai_agent"))
                return BotInfoCategory.AiAgent;

            if (value.Equals("ai_assistant"))
                return BotInfoCategory.AiAssistant;

            if (value.Equals("ai_browser"))
                return BotInfoCategory.AiBrowser;

            if (value.Equals("ai_crawler"))
                return BotInfoCategory.AiCrawler;

            if (value.Equals("ai_search"))
                return BotInfoCategory.AiSearch;

            if (value.Equals("browser_automation"))
                return BotInfoCategory.BrowserAutomation;

            if (value.Equals("ecommerce"))
                return BotInfoCategory.Ecommerce;

            if (value.Equals("monitoring_and_analytics"))
                return BotInfoCategory.MonitoringAndAnalytics;

            if (value.Equals("other"))
                return BotInfoCategory.Other;

            if (value.Equals("scraping"))
                return BotInfoCategory.Scraping;

            if (value.Equals("security"))
                return BotInfoCategory.Security;

            if (value.Equals("search_engine_crawler"))
                return BotInfoCategory.SearchEngineCrawler;

            if (value.Equals("search_engine_optimization"))
                return BotInfoCategory.SearchEngineOptimization;

            if (value.Equals("unknown"))
                return BotInfoCategory.Unknown;

            return BotInfoCategory.UnsupportedValueSdkUpgradeRequired;
        }

        /// <summary>
        /// Converts the <see cref="BotInfoCategory"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(BotInfoCategory value)
        {
            if (value == BotInfoCategory.AdvertisingAndMarketing)
                return "advertising_and_marketing";

            if (value == BotInfoCategory.Aggregator)
                return "aggregator";

            if (value == BotInfoCategory.AiAgent)
                return "ai_agent";

            if (value == BotInfoCategory.AiAssistant)
                return "ai_assistant";

            if (value == BotInfoCategory.AiBrowser)
                return "ai_browser";

            if (value == BotInfoCategory.AiCrawler)
                return "ai_crawler";

            if (value == BotInfoCategory.AiSearch)
                return "ai_search";

            if (value == BotInfoCategory.BrowserAutomation)
                return "browser_automation";

            if (value == BotInfoCategory.Ecommerce)
                return "ecommerce";

            if (value == BotInfoCategory.MonitoringAndAnalytics)
                return "monitoring_and_analytics";

            if (value == BotInfoCategory.Other)
                return "other";

            if (value == BotInfoCategory.Scraping)
                return "scraping";

            if (value == BotInfoCategory.Security)
                return "security";

            if (value == BotInfoCategory.SearchEngineCrawler)
                return "search_engine_crawler";

            if (value == BotInfoCategory.SearchEngineOptimization)
                return "search_engine_optimization";

            if (value == BotInfoCategory.Unknown)
                return "unknown";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BotInfoCategory"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class BotInfoCategoryJsonConverter : JsonConverter<BotInfoCategory>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override BotInfoCategory Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            BotInfoCategory? result = rawValue == null
                ? null
                : BotInfoCategoryValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the BotInfoCategory to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="botInfoCategory"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, BotInfoCategory botInfoCategory, JsonSerializerOptions options)
        {
            writer.WriteStringValue(BotInfoCategoryValueConverter.ToJsonValue(botInfoCategory).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BotInfoCategory"/>
    /// </summary>
    public class BotInfoCategoryNullableJsonConverter : JsonConverter<BotInfoCategory?>
    {
        /// <summary>
        /// Returns a BotInfoCategory from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override BotInfoCategory? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            BotInfoCategory? result = rawValue == null
                ? null
                : BotInfoCategoryValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the BotInfoCategory to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="botInfoCategory"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, BotInfoCategory? botInfoCategory, JsonSerializerOptions options)
        {
            writer.WriteStringValue(botInfoCategory.HasValue ? BotInfoCategoryValueConverter.ToJsonValue(botInfoCategory.Value).ToString() : "null");
        }
    }
}
