// <auto-generated>
/* 
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Fingerprint.ServerSdk.Client;

namespace Fingerprint.ServerSdk.Model
{
    /// <summary>
    /// Native, SDK-collected mobile device identification signals (manufacturer, model, and OS version). Structurally separate from the top-level `device`, `os`, and `os_version` fields and from `browser_details`, all of which are derived from user-agent parsing rather than native SDK signals.
    /// </summary>
    public partial class DeviceDetails : IValidatableObject
    {


        /// <summary>
        /// Initializes a new instance of the <see cref="DeviceDetails" /> class.
        /// </summary>
        /// <param name="deviceManufacturer">Raw device manufacturer string as reported by the device OS. Not normalized: casing is vendor-defined (samsung, Xiaomi, OPPO, HUAWEI). Always `Apple` on iOS..</param>
        /// <param name="deviceModel">Raw device model identifier, as reported by the mobile OS..</param>
        /// <param name="osVersion">Mobile operating system version. Component count is not fixed and must not be assumed by consumers: iOS always reports `major.minor.patch` (e.g. `17.4.1`), while Android's precision varies by OS era and which raw signal resolved it — `major` only (`9`, `13`) since Android 10 dropped point releases, `major.minor` (`16.1`) from Android 16 (API 36+) reintroducing a minor component, or a genuine `major.minor.patch` (`8.1.0`) on pre-Android 10 devices that shipped real point releases. Never a fabricated/zero-padded component..</param>
        [JsonConstructor]
        public DeviceDetails(Option<string> deviceManufacturer = default, Option<string> deviceModel = default, Option<string> osVersion = default)
        {
            DeviceManufacturerOption = deviceManufacturer;
            DeviceModelOption = deviceModel;
            OsVersionOption = osVersion;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of DeviceManufacturer
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> DeviceManufacturerOption { get; private set; }

        /// <summary>
        /// Raw device manufacturer string as reported by the device OS. Not normalized: casing is vendor-defined (samsung, Xiaomi, OPPO, HUAWEI). Always `Apple` on iOS.
        /// </summary>
        /// <value>Raw device manufacturer string as reported by the device OS. Not normalized: casing is vendor-defined (samsung, Xiaomi, OPPO, HUAWEI). Always `Apple` on iOS.</value>
        [JsonPropertyName("device_manufacturer")]
        public string DeviceManufacturer { get { return this.DeviceManufacturerOption; } set { this.DeviceManufacturerOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of DeviceModel
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> DeviceModelOption { get; private set; }

        /// <summary>
        /// Raw device model identifier, as reported by the mobile OS.
        /// </summary>
        /// <value>Raw device model identifier, as reported by the mobile OS.</value>
        [JsonPropertyName("device_model")]
        public string DeviceModel { get { return this.DeviceModelOption; } set { this.DeviceModelOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of OsVersion
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> OsVersionOption { get; private set; }

        /// <summary>
        /// Mobile operating system version. Component count is not fixed and must not be assumed by consumers: iOS always reports `major.minor.patch` (e.g. `17.4.1`), while Android's precision varies by OS era and which raw signal resolved it — `major` only (`9`, `13`) since Android 10 dropped point releases, `major.minor` (`16.1`) from Android 16 (API 36+) reintroducing a minor component, or a genuine `major.minor.patch` (`8.1.0`) on pre-Android 10 devices that shipped real point releases. Never a fabricated/zero-padded component.
        /// </summary>
        /// <value>Mobile operating system version. Component count is not fixed and must not be assumed by consumers: iOS always reports `major.minor.patch` (e.g. `17.4.1`), while Android's precision varies by OS era and which raw signal resolved it — `major` only (`9`, `13`) since Android 10 dropped point releases, `major.minor` (`16.1`) from Android 16 (API 36+) reintroducing a minor component, or a genuine `major.minor.patch` (`8.1.0`) on pre-Android 10 devices that shipped real point releases. Never a fabricated/zero-padded component.</value>
        [JsonPropertyName("os_version")]
        public string OsVersion { get { return this.OsVersionOption; } set { this.OsVersionOption = new Option<string>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DeviceDetails {\n");
            sb.Append("  DeviceManufacturer: ").Append(DeviceManufacturer).Append("\n");
            sb.Append("  DeviceModel: ").Append(DeviceModel).Append("\n");
            sb.Append("  OsVersion: ").Append(OsVersion).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DeviceDetails" />
    /// </summary>
    public class DeviceDetailsJsonConverter : JsonConverter<DeviceDetails>
    {
        /// <summary>
        /// Deserializes json to <see cref="DeviceDetails" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override DeviceDetails Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string> deviceManufacturer = default;
            Option<string> deviceModel = default;
            Option<string> osVersion = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "device_manufacturer":
                            deviceManufacturer = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "device_model":
                            deviceModel = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "os_version":
                            osVersion = new Option<string>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (deviceManufacturer.IsSet && deviceManufacturer.Value == null)
                throw new ArgumentNullException(nameof(deviceManufacturer), "Property is not nullable for class DeviceDetails.");

            if (deviceModel.IsSet && deviceModel.Value == null)
                throw new ArgumentNullException(nameof(deviceModel), "Property is not nullable for class DeviceDetails.");

            if (osVersion.IsSet && osVersion.Value == null)
                throw new ArgumentNullException(nameof(osVersion), "Property is not nullable for class DeviceDetails.");

            return new DeviceDetails(deviceManufacturer, deviceModel, osVersion);
        }

        /// <summary>
        /// Serializes a <see cref="DeviceDetails" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="deviceDetails"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, DeviceDetails deviceDetails, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, deviceDetails, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="DeviceDetails" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="deviceDetails"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, DeviceDetails deviceDetails, JsonSerializerOptions jsonSerializerOptions)
        {
            if (deviceDetails.DeviceManufacturerOption.IsSet && deviceDetails.DeviceManufacturer == null)
                throw new ArgumentNullException(nameof(deviceDetails.DeviceManufacturer), "Property is required for class DeviceDetails.");

            if (deviceDetails.DeviceModelOption.IsSet && deviceDetails.DeviceModel == null)
                throw new ArgumentNullException(nameof(deviceDetails.DeviceModel), "Property is required for class DeviceDetails.");

            if (deviceDetails.OsVersionOption.IsSet && deviceDetails.OsVersion == null)
                throw new ArgumentNullException(nameof(deviceDetails.OsVersion), "Property is required for class DeviceDetails.");

            if (deviceDetails.DeviceManufacturerOption.IsSet)
                writer.WriteString("device_manufacturer", deviceDetails.DeviceManufacturer);

            if (deviceDetails.DeviceModelOption.IsSet)
                writer.WriteString("device_model", deviceDetails.DeviceModel);

            if (deviceDetails.OsVersionOption.IsSet)
                writer.WriteString("os_version", deviceDetails.OsVersion);
        }
    }
}
