// <auto-generated>
/* 
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Fingerprint.ServerSdk.Client;

namespace Fingerprint.ServerSdk.Model
{
    /// <summary>
    /// EdgeRequestHeadersInner
    /// </summary>
    public partial class EdgeRequestHeadersInner : IValidatableObject
    {


        /// <summary>
        /// Initializes a new instance of the <see cref="EdgeRequestHeadersInner" /> class.
        /// </summary>
        /// <param name="name">Header name as forwarded by your server. Headers must be valid according to RFC 7230 and will be canonicalized according to RFC 9112. (required).</param>
        /// <param name="value">Value of a single forwarded header entry. Be careful to preserve the original encoding and escaping. For example, do not double escape quotes. (required).</param>
        [JsonConstructor]
        public EdgeRequestHeadersInner(string name, string value)
        {
            Name = name;
            Value = value;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Header name as forwarded by your server. Headers must be valid according to RFC 7230 and will be canonicalized according to RFC 9112.
        /// </summary>
        /// <value>Header name as forwarded by your server. Headers must be valid according to RFC 7230 and will be canonicalized according to RFC 9112.</value>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Value of a single forwarded header entry. Be careful to preserve the original encoding and escaping. For example, do not double escape quotes.
        /// </summary>
        /// <value>Value of a single forwarded header entry. Be careful to preserve the original encoding and escaping. For example, do not double escape quotes.</value>
        [JsonPropertyName("value")]
        public string Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EdgeRequestHeadersInner {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EdgeRequestHeadersInner" />
    /// </summary>
    public class EdgeRequestHeadersInnerJsonConverter : JsonConverter<EdgeRequestHeadersInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="EdgeRequestHeadersInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EdgeRequestHeadersInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string> name = default;
            Option<string> value = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "value":
                            value = new Option<string>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class EdgeRequestHeadersInner.", nameof(name));

            if (!value.IsSet)
                throw new ArgumentException("Property is required for class EdgeRequestHeadersInner.", nameof(value));

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class EdgeRequestHeadersInner.");

            if (value.IsSet && value.Value == null)
                throw new ArgumentNullException(nameof(value), "Property is not nullable for class EdgeRequestHeadersInner.");

            return new EdgeRequestHeadersInner(name.Value, value.Value);
        }

        /// <summary>
        /// Serializes a <see cref="EdgeRequestHeadersInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="edgeRequestHeadersInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EdgeRequestHeadersInner edgeRequestHeadersInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, edgeRequestHeadersInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EdgeRequestHeadersInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="edgeRequestHeadersInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EdgeRequestHeadersInner edgeRequestHeadersInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (edgeRequestHeadersInner.Name == null)
                throw new ArgumentNullException(nameof(edgeRequestHeadersInner.Name), "Property is required for class EdgeRequestHeadersInner.");

            if (edgeRequestHeadersInner.Value == null)
                throw new ArgumentNullException(nameof(edgeRequestHeadersInner.Value), "Property is required for class EdgeRequestHeadersInner.");

            writer.WriteString("name", edgeRequestHeadersInner.Name);

            writer.WriteString("value", edgeRequestHeadersInner.Value);
        }
    }
}
