// <auto-generated>
/* 
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Fingerprint.ServerSdk.Client;

namespace Fingerprint.ServerSdk.Model
{
    /// <summary>
    /// HTTP request metadata (including the HTTP method, headers and IP address) sent by you (your server) to the Fingerprint API for IP and bot analysis. To improve accuracy, retain as much of the original semantics of the HTTP request as possible. For example, preserve the order of the request headers and their capitalization. At least one of `ipv4_address` or `ipv6_address` must be provided; a request with neither is rejected with a `400` error. If both IPv4 and IPv6 are provided, IP intelligence will be provided for each address. If an IPv4-mapped IPv6 address is provided in the `ipv6_address` request property, the IP intelligence will be provided in the `ipv4_address` property of the response.
    /// </summary>
    public partial class EdgeRequest : IValidatableObject
    {


        /// <summary>
        /// Initializes a new instance of the <see cref="EdgeRequest" /> class.
        /// </summary>
        /// <param name="headers">Ordered header entries from the request made to your server. Each entry represents one header line. If one header name appears as multiple lines, send each as a separate item in the array.  Headers that contain authentication or session data must still be included, but with their value set to an empty string. This includes headers like `Authorization` and `Cookie`, but may contain more depending on your specific project, for instance `Proxy-Authenticate` or `X-Api-Key`. Omitting the headers entirely changes the shape of the request and can affect detection. Never forward the real secret values.  Whenever possible, we recommend preserving header order and capitalization to provide the best accuracy, however it’s not a strict requirement if your runtime does not maintain http header order or canonicalizes header names.  (required).</param>
        /// <param name="method">The original HTTP method of the request. If supported in your runtime, preserve the original casing. (required).</param>
        /// <param name="url">Absolute URL of the request, without a \\#fragment suffix. Only HTTP and HTTPS schemes are supported. (required).</param>
        /// <param name="ipv4Address">Client IPv4 address observed by your server..</param>
        /// <param name="ipv6Address">Client IPv6 address observed by your server..</param>
        /// <param name="linkedId">A customer-provided id that was sent with the request..</param>
        /// <param name="tags">A customer-provided value or an object that was sent with the identification request or updated later..</param>
        [JsonConstructor]
        public EdgeRequest(List<EdgeRequestHeadersInner> headers, string method, string url, Option<string> ipv4Address = default, Option<string> ipv6Address = default, Option<string> linkedId = default, Option<Dictionary<string, Object>> tags = default)
        {
            Headers = headers;
            Method = method;
            Url = url;
            Ipv4AddressOption = ipv4Address;
            Ipv6AddressOption = ipv6Address;
            LinkedIdOption = linkedId;
            TagsOption = tags;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Ordered header entries from the request made to your server. Each entry represents one header line. If one header name appears as multiple lines, send each as a separate item in the array.  Headers that contain authentication or session data must still be included, but with their value set to an empty string. This includes headers like `Authorization` and `Cookie`, but may contain more depending on your specific project, for instance `Proxy-Authenticate` or `X-Api-Key`. Omitting the headers entirely changes the shape of the request and can affect detection. Never forward the real secret values.  Whenever possible, we recommend preserving header order and capitalization to provide the best accuracy, however it’s not a strict requirement if your runtime does not maintain http header order or canonicalizes header names. 
        /// </summary>
        /// <value>Ordered header entries from the request made to your server. Each entry represents one header line. If one header name appears as multiple lines, send each as a separate item in the array.  Headers that contain authentication or session data must still be included, but with their value set to an empty string. This includes headers like `Authorization` and `Cookie`, but may contain more depending on your specific project, for instance `Proxy-Authenticate` or `X-Api-Key`. Omitting the headers entirely changes the shape of the request and can affect detection. Never forward the real secret values.  Whenever possible, we recommend preserving header order and capitalization to provide the best accuracy, however it’s not a strict requirement if your runtime does not maintain http header order or canonicalizes header names. </value>
        [JsonPropertyName("headers")]
        public List<EdgeRequestHeadersInner> Headers { get; set; }

        /// <summary>
        /// The original HTTP method of the request. If supported in your runtime, preserve the original casing.
        /// </summary>
        /// <value>The original HTTP method of the request. If supported in your runtime, preserve the original casing.</value>
        [JsonPropertyName("method")]
        public string Method { get; set; }

        /// <summary>
        /// Absolute URL of the request, without a \\#fragment suffix. Only HTTP and HTTPS schemes are supported.
        /// </summary>
        /// <value>Absolute URL of the request, without a \\#fragment suffix. Only HTTP and HTTPS schemes are supported.</value>
        [JsonPropertyName("url")]
        public string Url { get; set; }

        /// <summary>
        /// Used to track the state of Ipv4Address
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> Ipv4AddressOption { get; private set; }

        /// <summary>
        /// Client IPv4 address observed by your server.
        /// </summary>
        /// <value>Client IPv4 address observed by your server.</value>
        [JsonPropertyName("ipv4_address")]
        public string Ipv4Address { get { return this.Ipv4AddressOption; } set { this.Ipv4AddressOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of Ipv6Address
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> Ipv6AddressOption { get; private set; }

        /// <summary>
        /// Client IPv6 address observed by your server.
        /// </summary>
        /// <value>Client IPv6 address observed by your server.</value>
        [JsonPropertyName("ipv6_address")]
        public string Ipv6Address { get { return this.Ipv6AddressOption; } set { this.Ipv6AddressOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of LinkedId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> LinkedIdOption { get; private set; }

        /// <summary>
        /// A customer-provided id that was sent with the request.
        /// </summary>
        /// <value>A customer-provided id that was sent with the request.</value>
        [JsonPropertyName("linked_id")]
        public string LinkedId { get { return this.LinkedIdOption; } set { this.LinkedIdOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of Tags
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, Object>> TagsOption { get; private set; }

        /// <summary>
        /// A customer-provided value or an object that was sent with the identification request or updated later.
        /// </summary>
        /// <value>A customer-provided value or an object that was sent with the identification request or updated later.</value>
        [JsonPropertyName("tags")]
        public Dictionary<string, Object> Tags { get { return this.TagsOption; } set { this.TagsOption = new Option<Dictionary<string, Object>>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EdgeRequest {\n");
            sb.Append("  Headers: ").Append(Headers).Append("\n");
            sb.Append("  Method: ").Append(Method).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  Ipv4Address: ").Append(Ipv4Address).Append("\n");
            sb.Append("  Ipv6Address: ").Append(Ipv6Address).Append("\n");
            sb.Append("  LinkedId: ").Append(LinkedId).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EdgeRequest" />
    /// </summary>
    public class EdgeRequestJsonConverter : JsonConverter<EdgeRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="EdgeRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EdgeRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<EdgeRequestHeadersInner>> headers = default;
            Option<string> method = default;
            Option<string> url = default;
            Option<string> ipv4Address = default;
            Option<string> ipv6Address = default;
            Option<string> linkedId = default;
            Option<Dictionary<string, Object>> tags = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "headers":
                            headers = new Option<List<EdgeRequestHeadersInner>>(JsonSerializer.Deserialize<List<EdgeRequestHeadersInner>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "method":
                            method = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "url":
                            url = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "ipv4_address":
                            ipv4Address = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "ipv6_address":
                            ipv6Address = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "linked_id":
                            linkedId = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "tags":
                            tags = new Option<Dictionary<string, Object>>(JsonSerializer.Deserialize<Dictionary<string, Object>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!headers.IsSet)
                throw new ArgumentException("Property is required for class EdgeRequest.", nameof(headers));

            if (!method.IsSet)
                throw new ArgumentException("Property is required for class EdgeRequest.", nameof(method));

            if (!url.IsSet)
                throw new ArgumentException("Property is required for class EdgeRequest.", nameof(url));

            if (headers.IsSet && headers.Value == null)
                throw new ArgumentNullException(nameof(headers), "Property is not nullable for class EdgeRequest.");

            if (method.IsSet && method.Value == null)
                throw new ArgumentNullException(nameof(method), "Property is not nullable for class EdgeRequest.");

            if (url.IsSet && url.Value == null)
                throw new ArgumentNullException(nameof(url), "Property is not nullable for class EdgeRequest.");

            if (ipv4Address.IsSet && ipv4Address.Value == null)
                throw new ArgumentNullException(nameof(ipv4Address), "Property is not nullable for class EdgeRequest.");

            if (ipv6Address.IsSet && ipv6Address.Value == null)
                throw new ArgumentNullException(nameof(ipv6Address), "Property is not nullable for class EdgeRequest.");

            if (linkedId.IsSet && linkedId.Value == null)
                throw new ArgumentNullException(nameof(linkedId), "Property is not nullable for class EdgeRequest.");

            if (tags.IsSet && tags.Value == null)
                throw new ArgumentNullException(nameof(tags), "Property is not nullable for class EdgeRequest.");

            return new EdgeRequest(headers.Value, method.Value, url.Value, ipv4Address, ipv6Address, linkedId, tags);
        }

        /// <summary>
        /// Serializes a <see cref="EdgeRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="edgeRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EdgeRequest edgeRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, edgeRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EdgeRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="edgeRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EdgeRequest edgeRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (edgeRequest.Headers == null)
                throw new ArgumentNullException(nameof(edgeRequest.Headers), "Property is required for class EdgeRequest.");

            if (edgeRequest.Method == null)
                throw new ArgumentNullException(nameof(edgeRequest.Method), "Property is required for class EdgeRequest.");

            if (edgeRequest.Url == null)
                throw new ArgumentNullException(nameof(edgeRequest.Url), "Property is required for class EdgeRequest.");

            if (edgeRequest.Ipv4AddressOption.IsSet && edgeRequest.Ipv4Address == null)
                throw new ArgumentNullException(nameof(edgeRequest.Ipv4Address), "Property is required for class EdgeRequest.");

            if (edgeRequest.Ipv6AddressOption.IsSet && edgeRequest.Ipv6Address == null)
                throw new ArgumentNullException(nameof(edgeRequest.Ipv6Address), "Property is required for class EdgeRequest.");

            if (edgeRequest.LinkedIdOption.IsSet && edgeRequest.LinkedId == null)
                throw new ArgumentNullException(nameof(edgeRequest.LinkedId), "Property is required for class EdgeRequest.");

            if (edgeRequest.TagsOption.IsSet && edgeRequest.Tags == null)
                throw new ArgumentNullException(nameof(edgeRequest.Tags), "Property is required for class EdgeRequest.");

            writer.WritePropertyName("headers");
            JsonSerializer.Serialize(writer, edgeRequest.Headers, jsonSerializerOptions);
            writer.WriteString("method", edgeRequest.Method);

            writer.WriteString("url", edgeRequest.Url);

            if (edgeRequest.Ipv4AddressOption.IsSet)
                writer.WriteString("ipv4_address", edgeRequest.Ipv4Address);

            if (edgeRequest.Ipv6AddressOption.IsSet)
                writer.WriteString("ipv6_address", edgeRequest.Ipv6Address);

            if (edgeRequest.LinkedIdOption.IsSet)
                writer.WriteString("linked_id", edgeRequest.LinkedId);

            if (edgeRequest.TagsOption.IsSet)
            {
                writer.WritePropertyName("tags");
                JsonSerializer.Serialize(writer, edgeRequest.Tags, jsonSerializerOptions);
            }
        }
    }
}
