// <auto-generated>
/* 
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Fingerprint.ServerSdk.Client;

namespace Fingerprint.ServerSdk.Model
{
    /// <summary>
    /// Identifies how the event was generated. - `device` - the event was generated by the JS agent or a mobile SDK running on an end-user device. - `edge` - the event was generated by the Automation Intelligence API (`/edge` endpoint), analyzing a request intercepted at the edge. 
    /// </summary>
    /// <value>Identifies how the event was generated. - `device` - the event was generated by the JS agent or a mobile SDK running on an end-user device. - `edge` - the event was generated by the Automation Intelligence API (`/edge` endpoint), analyzing a request intercepted at the edge. </value>
    public enum EventSource
    {
        /// <summary>
        /// Enum Device for value: device
        /// </summary>
        Device = 1,

        /// <summary>
        /// Enum Edge for value: edge
        /// </summary>
        Edge = 2,

        /// <summary>
        /// Catch-all value used when the API returns an enum value that this version of the SDK does not recognize. Upgrade the SDK to a version that supports the value.
        /// </summary>
        UnsupportedValueSdkUpgradeRequired = -1
    }

    /// <summary>
    /// Converts <see cref="EventSource"/> to and from the JSON value
    /// </summary>
    public static class EventSourceValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="EventSource"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static EventSource FromString(string value)
        {
            if (value.Equals("device"))
                return EventSource.Device;

            if (value.Equals("edge"))
                return EventSource.Edge;

            throw new NotImplementedException($"Could not convert value to type EventSource: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="EventSource"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static EventSource? FromStringOrDefault(string value)
        {
            if (value.Equals("device"))
                return EventSource.Device;

            if (value.Equals("edge"))
                return EventSource.Edge;

            return EventSource.UnsupportedValueSdkUpgradeRequired;
        }

        /// <summary>
        /// Converts the <see cref="EventSource"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(EventSource value)
        {
            if (value == EventSource.Device)
                return "device";

            if (value == EventSource.Edge)
                return "edge";

            // Serialize the catch-all value rather than throwing, so models holding an enum value
            // this SDK version does not support can still be re-serialized. The original (unsupported)
            // value is not preserved.
            if (value == EventSource.UnsupportedValueSdkUpgradeRequired)
                return "unsupported_value_sdk_upgrade_required";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EventSource"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class EventSourceJsonConverter : JsonConverter<EventSource>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override EventSource Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            EventSource? result = rawValue == null
                ? null
                : EventSourceValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the EventSource to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="eventSource"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, EventSource eventSource, JsonSerializerOptions options)
        {
            writer.WriteStringValue(EventSourceValueConverter.ToJsonValue(eventSource).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EventSource"/>
    /// </summary>
    public class EventSourceNullableJsonConverter : JsonConverter<EventSource?>
    {
        /// <summary>
        /// Returns a EventSource from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override EventSource? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            EventSource? result = rawValue == null
                ? null
                : EventSourceValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the EventSource to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="eventSource"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, EventSource? eventSource, JsonSerializerOptions options)
        {
            writer.WriteStringValue(eventSource.HasValue ? EventSourceValueConverter.ToJsonValue(eventSource.Value).ToString() : "null");
        }
    }
}
