// <auto-generated>
/* 
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Fingerprint.ServerSdk.Client;

namespace Fingerprint.ServerSdk.Model
{
    /// <summary>
    /// IP and bot analysis for an event generated by the Automation Intelligence API (`/edge` endpoint). No client-side collection agent is involved, so Identification (`visitor_id`) and device-telemetry-derived Smart Signals are not available. 
    /// </summary>
    public partial class EventEdge : IValidatableObject
    {


        /// <summary>
        /// Initializes a new instance of the <see cref="EventEdge" /> class.
        /// </summary>
        /// <param name="eventId">Unique identifier of the user's request. The first portion of the event_id is a unix epoch milliseconds timestamp.  (required).</param>
        /// <param name="timestamp">Timestamp of the event with millisecond precision in Unix time. (required).</param>
        /// <param name="ipInfo">ipInfo (required).</param>
        /// <param name="source">source (required).</param>
        /// <param name="linkedId">A customer-provided id that was sent with the request..</param>
        /// <param name="tags">A customer-provided value or an object that was sent with the identification request or updated later..</param>
        /// <param name="url">Page URL from which the request was sent..</param>
        /// <param name="botInfo">botInfo.</param>
        /// <param name="proxy">IP address was used by a public proxy provider or belonged to a known recent residential proxy .</param>
        /// <param name="proxyConfidence">proxyConfidence.</param>
        /// <param name="proxyDetails">proxyDetails.</param>
        /// <param name="vpn">VPN or other anonymizing service has been used when sending the request. .</param>
        /// <param name="vpnConfidence">vpnConfidence.</param>
        /// <param name="vpnMethods">vpnMethods.</param>
        [JsonConstructor]
        public EventEdge(string eventId, long timestamp, IPInfo ipInfo, EventSource source, Option<string> linkedId = default, Option<Dictionary<string, Object>> tags = default, Option<string> url = default, Option<BotInfo> botInfo = default, Option<bool?> proxy = default, Option<ProxyConfidence?> proxyConfidence = default, Option<ProxyDetails> proxyDetails = default, Option<bool?> vpn = default, Option<VpnConfidence?> vpnConfidence = default, Option<VpnMethods> vpnMethods = default)
        {
            EventId = eventId;
            Timestamp = timestamp;
            IpInfo = ipInfo;
            Source = source;
            LinkedIdOption = linkedId;
            TagsOption = tags;
            UrlOption = url;
            BotInfoOption = botInfo;
            ProxyOption = proxy;
            ProxyConfidenceOption = proxyConfidence;
            ProxyDetailsOption = proxyDetails;
            VpnOption = vpn;
            VpnConfidenceOption = vpnConfidence;
            VpnMethodsOption = vpnMethods;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Source
        /// </summary>
        [JsonPropertyName("source")]
        public EventSource Source { get; set; }

        /// <summary>
        /// Used to track the state of ProxyConfidence
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ProxyConfidence?> ProxyConfidenceOption { get; private set; }

        /// <summary>
        /// Gets or Sets ProxyConfidence
        /// </summary>
        [JsonPropertyName("proxy_confidence")]
        public ProxyConfidence? ProxyConfidence { get { return this.ProxyConfidenceOption; } set { this.ProxyConfidenceOption = new Option<ProxyConfidence?>(value); } }

        /// <summary>
        /// Used to track the state of VpnConfidence
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<VpnConfidence?> VpnConfidenceOption { get; private set; }

        /// <summary>
        /// Gets or Sets VpnConfidence
        /// </summary>
        [JsonPropertyName("vpn_confidence")]
        public VpnConfidence? VpnConfidence { get { return this.VpnConfidenceOption; } set { this.VpnConfidenceOption = new Option<VpnConfidence?>(value); } }

        /// <summary>
        /// Unique identifier of the user's request. The first portion of the event_id is a unix epoch milliseconds timestamp. 
        /// </summary>
        /// <value>Unique identifier of the user's request. The first portion of the event_id is a unix epoch milliseconds timestamp. </value>
        [JsonPropertyName("event_id")]
        public string EventId { get; set; }

        /// <summary>
        /// Timestamp of the event with millisecond precision in Unix time.
        /// </summary>
        /// <value>Timestamp of the event with millisecond precision in Unix time.</value>
        [JsonPropertyName("timestamp")]
        public long Timestamp { get; set; }

        /// <summary>
        /// Gets or Sets IpInfo
        /// </summary>
        [JsonPropertyName("ip_info")]
        public IPInfo IpInfo { get; set; }

        /// <summary>
        /// Used to track the state of LinkedId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> LinkedIdOption { get; private set; }

        /// <summary>
        /// A customer-provided id that was sent with the request.
        /// </summary>
        /// <value>A customer-provided id that was sent with the request.</value>
        [JsonPropertyName("linked_id")]
        public string LinkedId { get { return this.LinkedIdOption; } set { this.LinkedIdOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of Tags
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, Object>> TagsOption { get; private set; }

        /// <summary>
        /// A customer-provided value or an object that was sent with the identification request or updated later.
        /// </summary>
        /// <value>A customer-provided value or an object that was sent with the identification request or updated later.</value>
        [JsonPropertyName("tags")]
        public Dictionary<string, Object> Tags { get { return this.TagsOption; } set { this.TagsOption = new Option<Dictionary<string, Object>>(value); } }

        /// <summary>
        /// Used to track the state of Url
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> UrlOption { get; private set; }

        /// <summary>
        /// Page URL from which the request was sent.
        /// </summary>
        /// <value>Page URL from which the request was sent.</value>
        [JsonPropertyName("url")]
        public string Url { get { return this.UrlOption; } set { this.UrlOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of BotInfo
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<BotInfo> BotInfoOption { get; private set; }

        /// <summary>
        /// Gets or Sets BotInfo
        /// </summary>
        [JsonPropertyName("bot_info")]
        public BotInfo BotInfo { get { return this.BotInfoOption; } set { this.BotInfoOption = new Option<BotInfo>(value); } }

        /// <summary>
        /// Used to track the state of Proxy
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> ProxyOption { get; private set; }

        /// <summary>
        /// IP address was used by a public proxy provider or belonged to a known recent residential proxy 
        /// </summary>
        /// <value>IP address was used by a public proxy provider or belonged to a known recent residential proxy </value>
        [JsonPropertyName("proxy")]
        public bool? Proxy { get { return this.ProxyOption; } set { this.ProxyOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of ProxyDetails
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ProxyDetails> ProxyDetailsOption { get; private set; }

        /// <summary>
        /// Gets or Sets ProxyDetails
        /// </summary>
        [JsonPropertyName("proxy_details")]
        public ProxyDetails ProxyDetails { get { return this.ProxyDetailsOption; } set { this.ProxyDetailsOption = new Option<ProxyDetails>(value); } }

        /// <summary>
        /// Used to track the state of Vpn
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> VpnOption { get; private set; }

        /// <summary>
        /// VPN or other anonymizing service has been used when sending the request. 
        /// </summary>
        /// <value>VPN or other anonymizing service has been used when sending the request. </value>
        [JsonPropertyName("vpn")]
        public bool? Vpn { get { return this.VpnOption; } set { this.VpnOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of VpnMethods
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<VpnMethods> VpnMethodsOption { get; private set; }

        /// <summary>
        /// Gets or Sets VpnMethods
        /// </summary>
        [JsonPropertyName("vpn_methods")]
        public VpnMethods VpnMethods { get { return this.VpnMethodsOption; } set { this.VpnMethodsOption = new Option<VpnMethods>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EventEdge {\n");
            sb.Append("  EventId: ").Append(EventId).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  IpInfo: ").Append(IpInfo).Append("\n");
            sb.Append("  Source: ").Append(Source).Append("\n");
            sb.Append("  LinkedId: ").Append(LinkedId).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  BotInfo: ").Append(BotInfo).Append("\n");
            sb.Append("  Proxy: ").Append(Proxy).Append("\n");
            sb.Append("  ProxyConfidence: ").Append(ProxyConfidence).Append("\n");
            sb.Append("  ProxyDetails: ").Append(ProxyDetails).Append("\n");
            sb.Append("  Vpn: ").Append(Vpn).Append("\n");
            sb.Append("  VpnConfidence: ").Append(VpnConfidence).Append("\n");
            sb.Append("  VpnMethods: ").Append(VpnMethods).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EventEdge" />
    /// </summary>
    public class EventEdgeJsonConverter : JsonConverter<EventEdge>
    {
        /// <summary>
        /// Deserializes json to <see cref="EventEdge" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EventEdge Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string> eventId = default;
            Option<long?> timestamp = default;
            Option<IPInfo> ipInfo = default;
            Option<EventSource?> source = default;
            Option<string> linkedId = default;
            Option<Dictionary<string, Object>> tags = default;
            Option<string> url = default;
            Option<BotInfo> botInfo = default;
            Option<bool?> proxy = default;
            Option<ProxyConfidence?> proxyConfidence = default;
            Option<ProxyDetails> proxyDetails = default;
            Option<bool?> vpn = default;
            Option<VpnConfidence?> vpnConfidence = default;
            Option<VpnMethods> vpnMethods = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "event_id":
                            eventId = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "timestamp":
                            timestamp = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "ip_info":
                            ipInfo = new Option<IPInfo>(JsonSerializer.Deserialize<IPInfo>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "source":
                            string sourceRawValue = utf8JsonReader.GetString();
                            if (sourceRawValue != null)
                                source = new Option<EventSource?>(EventSourceValueConverter.FromStringOrDefault(sourceRawValue));
                            break;
                        case "linked_id":
                            linkedId = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "tags":
                            tags = new Option<Dictionary<string, Object>>(JsonSerializer.Deserialize<Dictionary<string, Object>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "url":
                            url = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "bot_info":
                            botInfo = new Option<BotInfo>(JsonSerializer.Deserialize<BotInfo>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "proxy":
                            proxy = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "proxy_confidence":
                            string proxyConfidenceRawValue = utf8JsonReader.GetString();
                            if (proxyConfidenceRawValue != null)
                                proxyConfidence = new Option<ProxyConfidence?>(ProxyConfidenceValueConverter.FromStringOrDefault(proxyConfidenceRawValue));
                            break;
                        case "proxy_details":
                            proxyDetails = new Option<ProxyDetails>(JsonSerializer.Deserialize<ProxyDetails>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "vpn":
                            vpn = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "vpn_confidence":
                            string vpnConfidenceRawValue = utf8JsonReader.GetString();
                            if (vpnConfidenceRawValue != null)
                                vpnConfidence = new Option<VpnConfidence?>(VpnConfidenceValueConverter.FromStringOrDefault(vpnConfidenceRawValue));
                            break;
                        case "vpn_methods":
                            vpnMethods = new Option<VpnMethods>(JsonSerializer.Deserialize<VpnMethods>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!eventId.IsSet)
                throw new ArgumentException("Property is required for class EventEdge.", nameof(eventId));

            if (!timestamp.IsSet)
                throw new ArgumentException("Property is required for class EventEdge.", nameof(timestamp));

            if (!ipInfo.IsSet)
                throw new ArgumentException("Property is required for class EventEdge.", nameof(ipInfo));

            if (!source.IsSet)
                throw new ArgumentException("Property is required for class EventEdge.", nameof(source));

            if (eventId.IsSet && eventId.Value == null)
                throw new ArgumentNullException(nameof(eventId), "Property is not nullable for class EventEdge.");

            if (timestamp.IsSet && timestamp.Value == null)
                throw new ArgumentNullException(nameof(timestamp), "Property is not nullable for class EventEdge.");

            if (ipInfo.IsSet && ipInfo.Value == null)
                throw new ArgumentNullException(nameof(ipInfo), "Property is not nullable for class EventEdge.");

            if (source.IsSet && source.Value == null)
                throw new ArgumentNullException(nameof(source), "Property is not nullable for class EventEdge.");

            if (linkedId.IsSet && linkedId.Value == null)
                throw new ArgumentNullException(nameof(linkedId), "Property is not nullable for class EventEdge.");

            if (tags.IsSet && tags.Value == null)
                throw new ArgumentNullException(nameof(tags), "Property is not nullable for class EventEdge.");

            if (url.IsSet && url.Value == null)
                throw new ArgumentNullException(nameof(url), "Property is not nullable for class EventEdge.");

            if (botInfo.IsSet && botInfo.Value == null)
                throw new ArgumentNullException(nameof(botInfo), "Property is not nullable for class EventEdge.");

            if (proxy.IsSet && proxy.Value == null)
                throw new ArgumentNullException(nameof(proxy), "Property is not nullable for class EventEdge.");

            if (proxyConfidence.IsSet && proxyConfidence.Value == null)
                throw new ArgumentNullException(nameof(proxyConfidence), "Property is not nullable for class EventEdge.");

            if (proxyDetails.IsSet && proxyDetails.Value == null)
                throw new ArgumentNullException(nameof(proxyDetails), "Property is not nullable for class EventEdge.");

            if (vpn.IsSet && vpn.Value == null)
                throw new ArgumentNullException(nameof(vpn), "Property is not nullable for class EventEdge.");

            if (vpnConfidence.IsSet && vpnConfidence.Value == null)
                throw new ArgumentNullException(nameof(vpnConfidence), "Property is not nullable for class EventEdge.");

            if (vpnMethods.IsSet && vpnMethods.Value == null)
                throw new ArgumentNullException(nameof(vpnMethods), "Property is not nullable for class EventEdge.");

            return new EventEdge(eventId.Value, timestamp.Value.Value, ipInfo.Value, source.Value.Value, linkedId, tags, url, botInfo, proxy, proxyConfidence, proxyDetails, vpn, vpnConfidence, vpnMethods);
        }

        /// <summary>
        /// Serializes a <see cref="EventEdge" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="eventEdge"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EventEdge eventEdge, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, eventEdge, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EventEdge" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="eventEdge"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EventEdge eventEdge, JsonSerializerOptions jsonSerializerOptions)
        {
            if (eventEdge.EventId == null)
                throw new ArgumentNullException(nameof(eventEdge.EventId), "Property is required for class EventEdge.");

            if (eventEdge.IpInfo == null)
                throw new ArgumentNullException(nameof(eventEdge.IpInfo), "Property is required for class EventEdge.");

            if (eventEdge.LinkedIdOption.IsSet && eventEdge.LinkedId == null)
                throw new ArgumentNullException(nameof(eventEdge.LinkedId), "Property is required for class EventEdge.");

            if (eventEdge.TagsOption.IsSet && eventEdge.Tags == null)
                throw new ArgumentNullException(nameof(eventEdge.Tags), "Property is required for class EventEdge.");

            if (eventEdge.UrlOption.IsSet && eventEdge.Url == null)
                throw new ArgumentNullException(nameof(eventEdge.Url), "Property is required for class EventEdge.");

            if (eventEdge.BotInfoOption.IsSet && eventEdge.BotInfo == null)
                throw new ArgumentNullException(nameof(eventEdge.BotInfo), "Property is required for class EventEdge.");

            if (eventEdge.ProxyDetailsOption.IsSet && eventEdge.ProxyDetails == null)
                throw new ArgumentNullException(nameof(eventEdge.ProxyDetails), "Property is required for class EventEdge.");

            if (eventEdge.VpnMethodsOption.IsSet && eventEdge.VpnMethods == null)
                throw new ArgumentNullException(nameof(eventEdge.VpnMethods), "Property is required for class EventEdge.");

            writer.WriteString("event_id", eventEdge.EventId);

            writer.WriteNumber("timestamp", eventEdge.Timestamp);

            writer.WritePropertyName("ip_info");
            JsonSerializer.Serialize(writer, eventEdge.IpInfo, jsonSerializerOptions);
            var sourceRawValue = EventSourceValueConverter.ToJsonValue(eventEdge.Source);
            writer.WriteString("source", sourceRawValue);

            if (eventEdge.LinkedIdOption.IsSet)
                writer.WriteString("linked_id", eventEdge.LinkedId);

            if (eventEdge.TagsOption.IsSet)
            {
                writer.WritePropertyName("tags");
                JsonSerializer.Serialize(writer, eventEdge.Tags, jsonSerializerOptions);
            }
            if (eventEdge.UrlOption.IsSet)
                writer.WriteString("url", eventEdge.Url);

            if (eventEdge.BotInfoOption.IsSet)
            {
                writer.WritePropertyName("bot_info");
                JsonSerializer.Serialize(writer, eventEdge.BotInfo, jsonSerializerOptions);
            }
            if (eventEdge.ProxyOption.IsSet)
                writer.WriteBoolean("proxy", eventEdge.ProxyOption.Value.Value);

            if (eventEdge.ProxyConfidenceOption.IsSet)
            {
                var proxyConfidenceRawValue = ProxyConfidenceValueConverter.ToJsonValue(eventEdge.ProxyConfidence.Value);
                writer.WriteString("proxy_confidence", proxyConfidenceRawValue);
            }
            if (eventEdge.ProxyDetailsOption.IsSet)
            {
                writer.WritePropertyName("proxy_details");
                JsonSerializer.Serialize(writer, eventEdge.ProxyDetails, jsonSerializerOptions);
            }
            if (eventEdge.VpnOption.IsSet)
                writer.WriteBoolean("vpn", eventEdge.VpnOption.Value.Value);

            if (eventEdge.VpnConfidenceOption.IsSet)
            {
                var vpnConfidenceRawValue = VpnConfidenceValueConverter.ToJsonValue(eventEdge.VpnConfidence.Value);
                writer.WriteString("vpn_confidence", vpnConfidenceRawValue);
            }
            if (eventEdge.VpnMethodsOption.IsSet)
            {
                writer.WritePropertyName("vpn_methods");
                JsonSerializer.Serialize(writer, eventEdge.VpnMethods, jsonSerializerOptions);
            }
        }
    }
}
