// <auto-generated>
/* 
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Fingerprint.ServerSdk.Client;

namespace Fingerprint.ServerSdk.Model
{
    /// <summary>
    /// An identification event (`source: device`) or an Automation Intelligence event (`source: edge`).  Use `source` to tell them apart. Device events include Identification and device-derived Smart Signals. Edge events do not.  Consult the [Smart Signals reference](https://docs.fingerprint.com/docs/smart-signals-reference) for more details. 
    /// </summary>
    // SPIKE INTER-2457 — BREAKING CHANGE. DO NOT SHIP.
    // Event used to be a flat model with Identification. It is now a oneOf wrapper
    // with Event(EventDevice) / Event(EventEdge) constructors and no Identification
    // property. Callers of GetEventAsync / SearchEventsAsync / UnsealEventResponse
    // that read event.Identification fail to compile. Identification is on EventDevice.
    public partial class Event : IValidatableObject
    {


        /// <summary>
        /// Initializes a new instance of the <see cref="Event" /> class.
        /// </summary>
        /// <param name="eventDevice"></param>
        public Event(EventDevice eventDevice)
        {
            EventDevice = eventDevice;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Event" /> class.
        /// </summary>
        /// <param name="eventEdge"></param>
        public Event(EventEdge eventEdge)
        {
            EventEdge = eventEdge;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets EventDevice
        /// </summary>
        public EventDevice EventDevice { get; set; }

        /// <summary>
        /// Gets or Sets EventEdge
        /// </summary>
        public EventEdge EventEdge { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Event {\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Event" />
    /// </summary>
    public class EventJsonConverter : JsonConverter<Event>
    {
        /// <summary>
        /// Deserializes json to <see cref="Event" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Event Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<EventSource?> source = default;

            EventDevice eventDevice = null;
            EventEdge eventEdge = null;

            Utf8JsonReader utf8JsonReaderDiscriminator = utf8JsonReader;
            while (utf8JsonReaderDiscriminator.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReaderDiscriminator.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReaderDiscriminator.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReaderDiscriminator.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReaderDiscriminator.CurrentDepth)
                    break;

                if (utf8JsonReaderDiscriminator.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReaderDiscriminator.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReaderDiscriminator.GetString();
                    utf8JsonReaderDiscriminator.Read();
                    if (localVarJsonPropertyName.Equals("source"))
                    {
                        string discriminator = utf8JsonReaderDiscriminator.GetString();
                        if (discriminator.Equals("device"))
                        {
                            Utf8JsonReader utf8JsonReaderEventDevice = utf8JsonReader;
                            eventDevice = JsonSerializer.Deserialize<EventDevice>(ref utf8JsonReaderEventDevice, jsonSerializerOptions);
                        }
                        if (discriminator.Equals("edge"))
                        {
                            Utf8JsonReader utf8JsonReaderEventEdge = utf8JsonReader;
                            eventEdge = JsonSerializer.Deserialize<EventEdge>(ref utf8JsonReaderEventEdge, jsonSerializerOptions);
                        }
                    }
                }
            }

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "source":
                            string sourceRawValue = utf8JsonReader.GetString();
                            if (sourceRawValue != null)
                                source = new Option<EventSource?>(EventSourceValueConverter.FromStringOrDefault(sourceRawValue));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!source.IsSet)
                throw new ArgumentException("Property is required for class Event.", nameof(source));

            if (source.IsSet && source.Value == null)
                throw new ArgumentNullException(nameof(source), "Property is not nullable for class Event.");

            if (eventDevice != null)
                return new Event(eventDevice);

            if (eventEdge != null)
                return new Event(eventEdge);

            throw new JsonException();
        }

        /// <summary>
        /// Serializes a <see cref="Event" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="varEvent"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Event varEvent, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            if (varEvent.EventDevice != null)
            {
                EventDeviceJsonConverter eventDeviceJsonConverter = (EventDeviceJsonConverter) jsonSerializerOptions.Converters.First(c => c.CanConvert(varEvent.EventDevice.GetType()));
                eventDeviceJsonConverter.WriteProperties(writer, varEvent.EventDevice, jsonSerializerOptions);
            }

            if (varEvent.EventEdge != null)
            {
                EventEdgeJsonConverter eventEdgeJsonConverter = (EventEdgeJsonConverter) jsonSerializerOptions.Converters.First(c => c.CanConvert(varEvent.EventEdge.GetType()));
                eventEdgeJsonConverter.WriteProperties(writer, varEvent.EventEdge, jsonSerializerOptions);
            }

            WriteProperties(writer, varEvent, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Event" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="varEvent"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Event varEvent, JsonSerializerOptions jsonSerializerOptions)
        {

        }
    }
}
