// <auto-generated>
/* 
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Fingerprint.ServerSdk.Client;

namespace Fingerprint.ServerSdk.Model
{
    /// <summary>
    /// Only included for requests using incremental identification. - `partially_completed` - Indicates this event corresponds to a 'minimal' request. Smart Signals, even if included in your plan, are not computed; hence, their values must be ignored. - `completed` - Indicates this event corresponds to a 'complete' request. Smart Signals, if included in your plan, are computed; hence, their values are valid and relevant.  
    /// </summary>
    /// <value>Only included for requests using incremental identification. - `partially_completed` - Indicates this event corresponds to a 'minimal' request. Smart Signals, even if included in your plan, are not computed; hence, their values must be ignored. - `completed` - Indicates this event corresponds to a 'complete' request. Smart Signals, if included in your plan, are computed; hence, their values are valid and relevant.  </value>
    public enum IncrementalIdentificationStatus
    {
        /// <summary>
        /// Enum PartiallyCompleted for value: partially_completed
        /// </summary>
        PartiallyCompleted = 1,

        /// <summary>
        /// Enum Completed for value: completed
        /// </summary>
        Completed = 2,

        /// <summary>
        /// Catch-all value used when the API returns an enum value that this version of the SDK does not recognize. Upgrade the SDK to a version that supports the value.
        /// </summary>
        UnsupportedValueSdkUpgradeRequired = -1
    }

    /// <summary>
    /// Converts <see cref="IncrementalIdentificationStatus"/> to and from the JSON value
    /// </summary>
    public static class IncrementalIdentificationStatusValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="IncrementalIdentificationStatus"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static IncrementalIdentificationStatus FromString(string value)
        {
            if (value.Equals("partially_completed"))
                return IncrementalIdentificationStatus.PartiallyCompleted;

            if (value.Equals("completed"))
                return IncrementalIdentificationStatus.Completed;

            throw new NotImplementedException($"Could not convert value to type IncrementalIdentificationStatus: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="IncrementalIdentificationStatus"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static IncrementalIdentificationStatus? FromStringOrDefault(string value)
        {
            if (value.Equals("partially_completed"))
                return IncrementalIdentificationStatus.PartiallyCompleted;

            if (value.Equals("completed"))
                return IncrementalIdentificationStatus.Completed;

            return IncrementalIdentificationStatus.UnsupportedValueSdkUpgradeRequired;
        }

        /// <summary>
        /// Converts the <see cref="IncrementalIdentificationStatus"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(IncrementalIdentificationStatus value)
        {
            if (value == IncrementalIdentificationStatus.PartiallyCompleted)
                return "partially_completed";

            if (value == IncrementalIdentificationStatus.Completed)
                return "completed";

            // Serialize the catch-all value rather than throwing, so models holding an enum value
            // this SDK version does not support can still be re-serialized. The original (unsupported)
            // value is not preserved.
            if (value == IncrementalIdentificationStatus.UnsupportedValueSdkUpgradeRequired)
                return "unsupported_value_sdk_upgrade_required";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="IncrementalIdentificationStatus"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class IncrementalIdentificationStatusJsonConverter : JsonConverter<IncrementalIdentificationStatus>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override IncrementalIdentificationStatus Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            IncrementalIdentificationStatus? result = rawValue == null
                ? null
                : IncrementalIdentificationStatusValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the IncrementalIdentificationStatus to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="incrementalIdentificationStatus"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, IncrementalIdentificationStatus incrementalIdentificationStatus, JsonSerializerOptions options)
        {
            writer.WriteStringValue(IncrementalIdentificationStatusValueConverter.ToJsonValue(incrementalIdentificationStatus).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="IncrementalIdentificationStatus"/>
    /// </summary>
    public class IncrementalIdentificationStatusNullableJsonConverter : JsonConverter<IncrementalIdentificationStatus?>
    {
        /// <summary>
        /// Returns a IncrementalIdentificationStatus from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override IncrementalIdentificationStatus? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            IncrementalIdentificationStatus? result = rawValue == null
                ? null
                : IncrementalIdentificationStatusValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the IncrementalIdentificationStatus to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="incrementalIdentificationStatus"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, IncrementalIdentificationStatus? incrementalIdentificationStatus, JsonSerializerOptions options)
        {
            writer.WriteStringValue(incrementalIdentificationStatus.HasValue ? IncrementalIdentificationStatusValueConverter.ToJsonValue(incrementalIdentificationStatus.Value).ToString() : "null");
        }
    }
}
