// <auto-generated>
/* 
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Fingerprint.ServerSdk.Client;

namespace Fingerprint.ServerSdk.Model
{
    /// <summary>
    /// LabelsInner
    /// </summary>
    public partial class LabelsInner : IValidatableObject
    {


        /// <summary>
        /// Initializes a new instance of the <see cref="LabelsInner" /> class.
        /// </summary>
        /// <param name="label">label.</param>
        /// <param name="prediction">prediction.</param>
        /// <param name="mlScore">mlScore.</param>
        [JsonConstructor]
        public LabelsInner(Option<string> label = default, Option<bool?> prediction = default, Option<double?> mlScore = default)
        {
            LabelOption = label;
            PredictionOption = prediction;
            MlScoreOption = mlScore;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Label
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> LabelOption { get; private set; }

        /// <summary>
        /// Gets or Sets Label
        /// </summary>
        [JsonPropertyName("label")]
        public string Label { get { return this.LabelOption; } set { this.LabelOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of Prediction
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> PredictionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Prediction
        /// </summary>
        [JsonPropertyName("prediction")]
        public bool? Prediction { get { return this.PredictionOption; } set { this.PredictionOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of MlScore
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> MlScoreOption { get; private set; }

        /// <summary>
        /// Gets or Sets MlScore
        /// </summary>
        [JsonPropertyName("ml_score")]
        public double? MlScore { get { return this.MlScoreOption; } set { this.MlScoreOption = new Option<double?>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LabelsInner {\n");
            sb.Append("  Label: ").Append(Label).Append("\n");
            sb.Append("  Prediction: ").Append(Prediction).Append("\n");
            sb.Append("  MlScore: ").Append(MlScore).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // MlScore (double) maximum
            if (this.MlScoreOption.IsSet && this.MlScoreOption.Value > (double)1)
            {
                yield return new ValidationResult("Invalid value for MlScore, must be a value less than or equal to 1.", new [] { "MlScore" });
            }

            // MlScore (double) minimum
            if (this.MlScoreOption.IsSet && this.MlScoreOption.Value < (double)0)
            {
                yield return new ValidationResult("Invalid value for MlScore, must be a value greater than or equal to 0.", new [] { "MlScore" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="LabelsInner" />
    /// </summary>
    public class LabelsInnerJsonConverter : JsonConverter<LabelsInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="LabelsInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override LabelsInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string> label = default;
            Option<bool?> prediction = default;
            Option<double?> mlScore = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "label":
                            label = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "prediction":
                            prediction = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "ml_score":
                            mlScore = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (label.IsSet && label.Value == null)
                throw new ArgumentNullException(nameof(label), "Property is not nullable for class LabelsInner.");

            if (prediction.IsSet && prediction.Value == null)
                throw new ArgumentNullException(nameof(prediction), "Property is not nullable for class LabelsInner.");

            if (mlScore.IsSet && mlScore.Value == null)
                throw new ArgumentNullException(nameof(mlScore), "Property is not nullable for class LabelsInner.");

            return new LabelsInner(label, prediction, mlScore);
        }

        /// <summary>
        /// Serializes a <see cref="LabelsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="labelsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, LabelsInner labelsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, labelsInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="LabelsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="labelsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, LabelsInner labelsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (labelsInner.LabelOption.IsSet && labelsInner.Label == null)
                throw new ArgumentNullException(nameof(labelsInner.Label), "Property is required for class LabelsInner.");

            if (labelsInner.LabelOption.IsSet)
                writer.WriteString("label", labelsInner.Label);

            if (labelsInner.PredictionOption.IsSet)
                writer.WriteBoolean("prediction", labelsInner.PredictionOption.Value.Value);

            if (labelsInner.MlScoreOption.IsSet)
                writer.WriteNumber("ml_score", labelsInner.MlScoreOption.Value.Value);
        }
    }
}
