// <auto-generated>
/* 
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Fingerprint.ServerSdk.Client;

namespace Fingerprint.ServerSdk.Model
{
    /// <summary>
    /// The rarity percentile bucket of the device, indicating how uncommon the device configuration is compared to all observed devices.  > This Smart Signal is currently in beta and only available to select customers. If you are interested, please [contact our support team](https://fingerprint.com/support/). 
    /// </summary>
    /// <value>The rarity percentile bucket of the device, indicating how uncommon the device configuration is compared to all observed devices.  > This Smart Signal is currently in beta and only available to select customers. If you are interested, please [contact our support team](https://fingerprint.com/support/). </value>
    public enum RareDevicePercentileBucket
    {
        /// <summary>
        /// Enum P95 for value: &lt;p95
        /// </summary>
        P95 = 1,

        /// <summary>
        /// Enum P95P99 for value: p95-p99
        /// </summary>
        P95P99 = 2,

        /// <summary>
        /// Enum P99P995 for value: p99-p99.5
        /// </summary>
        P99P995 = 3,

        /// <summary>
        /// Enum P995P999 for value: p99.5-p99.9
        /// </summary>
        P995P999 = 4,

        /// <summary>
        /// Enum P999 for value: p99.9+
        /// </summary>
        P999 = 5,

        /// <summary>
        /// Enum NotSeen for value: not_seen
        /// </summary>
        NotSeen = 6
    }

    /// <summary>
    /// Converts <see cref="RareDevicePercentileBucket"/> to and from the JSON value
    /// </summary>
    public static class RareDevicePercentileBucketValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="RareDevicePercentileBucket"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static RareDevicePercentileBucket FromString(string value)
        {
            if (value.Equals("<p95"))
                return RareDevicePercentileBucket.P95;

            if (value.Equals("p95-p99"))
                return RareDevicePercentileBucket.P95P99;

            if (value.Equals("p99-p99.5"))
                return RareDevicePercentileBucket.P99P995;

            if (value.Equals("p99.5-p99.9"))
                return RareDevicePercentileBucket.P995P999;

            if (value.Equals("p99.9+"))
                return RareDevicePercentileBucket.P999;

            if (value.Equals("not_seen"))
                return RareDevicePercentileBucket.NotSeen;

            throw new NotImplementedException($"Could not convert value to type RareDevicePercentileBucket: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="RareDevicePercentileBucket"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static RareDevicePercentileBucket? FromStringOrDefault(string value)
        {
            if (value.Equals("<p95"))
                return RareDevicePercentileBucket.P95;

            if (value.Equals("p95-p99"))
                return RareDevicePercentileBucket.P95P99;

            if (value.Equals("p99-p99.5"))
                return RareDevicePercentileBucket.P99P995;

            if (value.Equals("p99.5-p99.9"))
                return RareDevicePercentileBucket.P995P999;

            if (value.Equals("p99.9+"))
                return RareDevicePercentileBucket.P999;

            if (value.Equals("not_seen"))
                return RareDevicePercentileBucket.NotSeen;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="RareDevicePercentileBucket"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(RareDevicePercentileBucket value)
        {
            if (value == RareDevicePercentileBucket.P95)
                return "<p95";

            if (value == RareDevicePercentileBucket.P95P99)
                return "p95-p99";

            if (value == RareDevicePercentileBucket.P99P995)
                return "p99-p99.5";

            if (value == RareDevicePercentileBucket.P995P999)
                return "p99.5-p99.9";

            if (value == RareDevicePercentileBucket.P999)
                return "p99.9+";

            if (value == RareDevicePercentileBucket.NotSeen)
                return "not_seen";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="RareDevicePercentileBucket"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class RareDevicePercentileBucketJsonConverter : JsonConverter<RareDevicePercentileBucket>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override RareDevicePercentileBucket Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            RareDevicePercentileBucket? result = rawValue == null
                ? null
                : RareDevicePercentileBucketValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the RareDevicePercentileBucket to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="rareDevicePercentileBucket"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, RareDevicePercentileBucket rareDevicePercentileBucket, JsonSerializerOptions options)
        {
            writer.WriteStringValue(RareDevicePercentileBucketValueConverter.ToJsonValue(rareDevicePercentileBucket).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="RareDevicePercentileBucket"/>
    /// </summary>
    public class RareDevicePercentileBucketNullableJsonConverter : JsonConverter<RareDevicePercentileBucket?>
    {
        /// <summary>
        /// Returns a RareDevicePercentileBucket from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override RareDevicePercentileBucket? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            RareDevicePercentileBucket? result = rawValue == null
                ? null
                : RareDevicePercentileBucketValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the RareDevicePercentileBucket to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="rareDevicePercentileBucket"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, RareDevicePercentileBucket? rareDevicePercentileBucket, JsonSerializerOptions options)
        {
            writer.WriteStringValue(rareDevicePercentileBucket.HasValue ? RareDevicePercentileBucketValueConverter.ToJsonValue(rareDevicePercentileBucket.Value).ToString() : "null");
        }
    }
}
