// <auto-generated>
/* 
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Fingerprint.ServerSdk.Client;

namespace Fingerprint.ServerSdk.Model
{
    /// <summary>
    /// SearchEventsEndParameter
    /// </summary>
    public partial class SearchEventsEndParameter : IValidatableObject
    {


        /// <summary>
        /// Initializes a new instance of the <see cref="SearchEventsEndParameter" /> class.
        /// </summary>
        /// <param name="long"></param>
        internal SearchEventsEndParameter(long @long)
        {
            Long = @long;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SearchEventsEndParameter" /> class.
        /// </summary>
        /// <param name="dateTime"></param>
        internal SearchEventsEndParameter(DateTime dateTime)
        {
            DateTime = dateTime;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Long
        /// </summary>
        /* <example>1769903999000</example> */
        public long? Long { get; set; }

        /// <summary>
        /// Gets or Sets DateTime
        /// </summary>
        /* <example>2026-01-31T23:59:59Z</example> */
        public DateTime? DateTime { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SearchEventsEndParameter {\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Formats the value contained by SearchEventsEndParameter as a parameter
        /// </summary>
        /// <returns>Formatted string.</returns>
        public string ToParameterString()
        {
            if (Long.HasValue)
            {
                return ClientUtils.ParameterToString(Long.Value);
            }
            if (DateTime.HasValue)
            {
                return ClientUtils.ParameterToString(DateTime.Value);
            }
            throw new InvalidOperationException("Value not set");
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SearchEventsEndParameter" />
    /// </summary>
    public class SearchEventsEndParameterJsonConverter : JsonConverter<SearchEventsEndParameter>
    {
        /// <summary>
        /// Deserializes json to <see cref="SearchEventsEndParameter" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SearchEventsEndParameter Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {

            long? varLong = default;
            DateTime? dateTime = default;

            var utf8JsonReaderLong = utf8JsonReader;
            ClientUtils.TryDeserialize<long?>(ref utf8JsonReaderLong, jsonSerializerOptions, out varLong);
            var utf8JsonReaderDateTime = utf8JsonReader;
            ClientUtils.TryDeserialize<DateTime?>(ref utf8JsonReaderDateTime, jsonSerializerOptions, out dateTime);

            if (varLong != null)
                return new SearchEventsEndParameter(varLong.Value);

            if (dateTime != null)
                return new SearchEventsEndParameter(dateTime.Value);

            throw new JsonException();
        }

        /// <summary>
        /// Serializes a <see cref="SearchEventsEndParameter" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="searchEventsEndParameter"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SearchEventsEndParameter searchEventsEndParameter, JsonSerializerOptions jsonSerializerOptions)
        {
            if (searchEventsEndParameter.Long.HasValue)
            {
                writer.WriteNumberValue(searchEventsEndParameter.Long.Value);
            }
            else if (searchEventsEndParameter.DateTime.HasValue)
            {
                DateTimeJsonConverter dateTimeJsonConverter = (DateTimeJsonConverter) jsonSerializerOptions.Converters.First(c => c.CanConvert(searchEventsEndParameter.DateTime.Value.GetType()));
                dateTimeJsonConverter.Write(writer, searchEventsEndParameter.DateTime.Value, jsonSerializerOptions);
            }
            else
            {
                throw new JsonException("Cannot serialize SearchEventsEndParameter because no oneOf variant is set.");
            }
        }
    }
}
