// <auto-generated>
/* 
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Fingerprint.ServerSdk.Client;

namespace Fingerprint.ServerSdk.Model
{
    /// <summary>
    /// Filter events by their Bot Info result, specifically:   - `all` - events where any kind of bot was detected.   - `none` - events where no bot was detected. 
    /// </summary>
    /// <value>Filter events by their Bot Info result, specifically:   - `all` - events where any kind of bot was detected.   - `none` - events where no bot was detected. </value>
    public enum SearchEventsBotInfo
    {
        /// <summary>
        /// Enum All for value: all
        /// </summary>
        All = 1,

        /// <summary>
        /// Enum None for value: none
        /// </summary>
        None = 2,

        /// <summary>
        /// Catch-all value used when the API returns an enum value that this version of the SDK does not recognize. Upgrade the SDK to a version that supports the value.
        /// </summary>
        UnsupportedValueSdkUpgradeRequired = -1
    }

    /// <summary>
    /// Converts <see cref="SearchEventsBotInfo"/> to and from the JSON value
    /// </summary>
    public static class SearchEventsBotInfoValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="SearchEventsBotInfo"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static SearchEventsBotInfo FromString(string value)
        {
            if (value.Equals("all"))
                return SearchEventsBotInfo.All;

            if (value.Equals("none"))
                return SearchEventsBotInfo.None;

            throw new NotImplementedException($"Could not convert value to type SearchEventsBotInfo: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="SearchEventsBotInfo"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static SearchEventsBotInfo? FromStringOrDefault(string value)
        {
            if (value.Equals("all"))
                return SearchEventsBotInfo.All;

            if (value.Equals("none"))
                return SearchEventsBotInfo.None;

            return SearchEventsBotInfo.UnsupportedValueSdkUpgradeRequired;
        }

        /// <summary>
        /// Converts the <see cref="SearchEventsBotInfo"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(SearchEventsBotInfo value)
        {
            if (value == SearchEventsBotInfo.All)
                return "all";

            if (value == SearchEventsBotInfo.None)
                return "none";

            // Serialize the catch-all value rather than throwing, so models holding an enum value
            // this SDK version does not support can still be re-serialized. The original (unsupported)
            // value is not preserved.
            if (value == SearchEventsBotInfo.UnsupportedValueSdkUpgradeRequired)
                return "unsupported_value_sdk_upgrade_required";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SearchEventsBotInfo"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class SearchEventsBotInfoJsonConverter : JsonConverter<SearchEventsBotInfo>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override SearchEventsBotInfo Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            SearchEventsBotInfo? result = rawValue == null
                ? null
                : SearchEventsBotInfoValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the SearchEventsBotInfo to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="searchEventsBotInfo"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, SearchEventsBotInfo searchEventsBotInfo, JsonSerializerOptions options)
        {
            writer.WriteStringValue(SearchEventsBotInfoValueConverter.ToJsonValue(searchEventsBotInfo).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SearchEventsBotInfo"/>
    /// </summary>
    public class SearchEventsBotInfoNullableJsonConverter : JsonConverter<SearchEventsBotInfo?>
    {
        /// <summary>
        /// Returns a SearchEventsBotInfo from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override SearchEventsBotInfo? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            SearchEventsBotInfo? result = rawValue == null
                ? null
                : SearchEventsBotInfoValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the SearchEventsBotInfo to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="searchEventsBotInfo"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, SearchEventsBotInfo? searchEventsBotInfo, JsonSerializerOptions options)
        {
            writer.WriteStringValue(searchEventsBotInfo.HasValue ? SearchEventsBotInfoValueConverter.ToJsonValue(searchEventsBotInfo.Value).ToString() : "null");
        }
    }
}
