// <auto-generated>
/* 
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Fingerprint.ServerSdk.Client;

namespace Fingerprint.ServerSdk.Model
{
    /// <summary>
    /// Filter events by Device Rarity percentile bucket. `<p95` - device configuration is in the bottom 95% (most common). `p95-p99` - device is in the 95th to 99th percentile. `p99-p99.5` - device is in the 99th to 99.5th percentile. `p99.5-p99.9` - device is in the 99.5th to 99.9th percentile. `p99.9+` - device is in the top 0.1% (rarest). `not_seen` - device configuration has never been observed before.  > This Smart Signal is currently in beta and only available to select customers. If you are interested, please [contact our support team](https://fingerprint.com/support/). 
    /// </summary>
    /// <value>Filter events by Device Rarity percentile bucket. `<p95` - device configuration is in the bottom 95% (most common). `p95-p99` - device is in the 95th to 99th percentile. `p99-p99.5` - device is in the 99th to 99.5th percentile. `p99.5-p99.9` - device is in the 99.5th to 99.9th percentile. `p99.9+` - device is in the top 0.1% (rarest). `not_seen` - device configuration has never been observed before.  > This Smart Signal is currently in beta and only available to select customers. If you are interested, please [contact our support team](https://fingerprint.com/support/). </value>
    public enum SearchEventsRareDevicePercentileBucket
    {
        /// <summary>
        /// Enum P95 for value: &lt;p95
        /// </summary>
        P95 = 1,

        /// <summary>
        /// Enum P95P99 for value: p95-p99
        /// </summary>
        P95P99 = 2,

        /// <summary>
        /// Enum P99P995 for value: p99-p99.5
        /// </summary>
        P99P995 = 3,

        /// <summary>
        /// Enum P995P999 for value: p99.5-p99.9
        /// </summary>
        P995P999 = 4,

        /// <summary>
        /// Enum P999 for value: p99.9+
        /// </summary>
        P999 = 5,

        /// <summary>
        /// Enum NotSeen for value: not_seen
        /// </summary>
        NotSeen = 6,

        /// <summary>
        /// Catch-all value used when the API returns an enum value that this version of the SDK does not recognize. Upgrade the SDK to a version that supports the value.
        /// </summary>
        UnsupportedValueSdkUpgradeRequired = -1
    }

    /// <summary>
    /// Converts <see cref="SearchEventsRareDevicePercentileBucket"/> to and from the JSON value
    /// </summary>
    public static class SearchEventsRareDevicePercentileBucketValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="SearchEventsRareDevicePercentileBucket"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static SearchEventsRareDevicePercentileBucket FromString(string value)
        {
            if (value.Equals("<p95"))
                return SearchEventsRareDevicePercentileBucket.P95;

            if (value.Equals("p95-p99"))
                return SearchEventsRareDevicePercentileBucket.P95P99;

            if (value.Equals("p99-p99.5"))
                return SearchEventsRareDevicePercentileBucket.P99P995;

            if (value.Equals("p99.5-p99.9"))
                return SearchEventsRareDevicePercentileBucket.P995P999;

            if (value.Equals("p99.9+"))
                return SearchEventsRareDevicePercentileBucket.P999;

            if (value.Equals("not_seen"))
                return SearchEventsRareDevicePercentileBucket.NotSeen;

            throw new NotImplementedException($"Could not convert value to type SearchEventsRareDevicePercentileBucket: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="SearchEventsRareDevicePercentileBucket"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static SearchEventsRareDevicePercentileBucket? FromStringOrDefault(string value)
        {
            if (value.Equals("<p95"))
                return SearchEventsRareDevicePercentileBucket.P95;

            if (value.Equals("p95-p99"))
                return SearchEventsRareDevicePercentileBucket.P95P99;

            if (value.Equals("p99-p99.5"))
                return SearchEventsRareDevicePercentileBucket.P99P995;

            if (value.Equals("p99.5-p99.9"))
                return SearchEventsRareDevicePercentileBucket.P995P999;

            if (value.Equals("p99.9+"))
                return SearchEventsRareDevicePercentileBucket.P999;

            if (value.Equals("not_seen"))
                return SearchEventsRareDevicePercentileBucket.NotSeen;

            return SearchEventsRareDevicePercentileBucket.UnsupportedValueSdkUpgradeRequired;
        }

        /// <summary>
        /// Converts the <see cref="SearchEventsRareDevicePercentileBucket"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(SearchEventsRareDevicePercentileBucket value)
        {
            if (value == SearchEventsRareDevicePercentileBucket.P95)
                return "<p95";

            if (value == SearchEventsRareDevicePercentileBucket.P95P99)
                return "p95-p99";

            if (value == SearchEventsRareDevicePercentileBucket.P99P995)
                return "p99-p99.5";

            if (value == SearchEventsRareDevicePercentileBucket.P995P999)
                return "p99.5-p99.9";

            if (value == SearchEventsRareDevicePercentileBucket.P999)
                return "p99.9+";

            if (value == SearchEventsRareDevicePercentileBucket.NotSeen)
                return "not_seen";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SearchEventsRareDevicePercentileBucket"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class SearchEventsRareDevicePercentileBucketJsonConverter : JsonConverter<SearchEventsRareDevicePercentileBucket>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override SearchEventsRareDevicePercentileBucket Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            SearchEventsRareDevicePercentileBucket? result = rawValue == null
                ? null
                : SearchEventsRareDevicePercentileBucketValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the SearchEventsRareDevicePercentileBucket to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="searchEventsRareDevicePercentileBucket"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, SearchEventsRareDevicePercentileBucket searchEventsRareDevicePercentileBucket, JsonSerializerOptions options)
        {
            writer.WriteStringValue(SearchEventsRareDevicePercentileBucketValueConverter.ToJsonValue(searchEventsRareDevicePercentileBucket).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SearchEventsRareDevicePercentileBucket"/>
    /// </summary>
    public class SearchEventsRareDevicePercentileBucketNullableJsonConverter : JsonConverter<SearchEventsRareDevicePercentileBucket?>
    {
        /// <summary>
        /// Returns a SearchEventsRareDevicePercentileBucket from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override SearchEventsRareDevicePercentileBucket? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            SearchEventsRareDevicePercentileBucket? result = rawValue == null
                ? null
                : SearchEventsRareDevicePercentileBucketValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the SearchEventsRareDevicePercentileBucket to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="searchEventsRareDevicePercentileBucket"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, SearchEventsRareDevicePercentileBucket? searchEventsRareDevicePercentileBucket, JsonSerializerOptions options)
        {
            writer.WriteStringValue(searchEventsRareDevicePercentileBucket.HasValue ? SearchEventsRareDevicePercentileBucketValueConverter.ToJsonValue(searchEventsRareDevicePercentileBucket.Value).ToString() : "null");
        }
    }
}
