// <auto-generated>
/* 
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Fingerprint.ServerSdk.Client;

namespace Fingerprint.ServerSdk.Model
{
    /// <summary>
    /// Filter events by their incremental identification status (`incremental_identification_status` property). Non incremental identification events are left out of the response. 
    /// </summary>
    /// <value>Filter events by their incremental identification status (`incremental_identification_status` property). Non incremental identification events are left out of the response. </value>
    public enum SearchEventsIncrementalIdentificationStatus
    {
        /// <summary>
        /// Enum PartiallyCompleted for value: partially_completed
        /// </summary>
        PartiallyCompleted = 1,

        /// <summary>
        /// Enum Completed for value: completed
        /// </summary>
        Completed = 2,

        /// <summary>
        /// Catch-all value used when the API returns an enum value that this version of the SDK does not recognize. Upgrade the SDK to a version that supports the value.
        /// </summary>
        UnsupportedValueSdkUpgradeRequired = -1
    }

    /// <summary>
    /// Converts <see cref="SearchEventsIncrementalIdentificationStatus"/> to and from the JSON value
    /// </summary>
    public static class SearchEventsIncrementalIdentificationStatusValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="SearchEventsIncrementalIdentificationStatus"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static SearchEventsIncrementalIdentificationStatus FromString(string value)
        {
            if (value.Equals("partially_completed"))
                return SearchEventsIncrementalIdentificationStatus.PartiallyCompleted;

            if (value.Equals("completed"))
                return SearchEventsIncrementalIdentificationStatus.Completed;

            throw new NotImplementedException($"Could not convert value to type SearchEventsIncrementalIdentificationStatus: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="SearchEventsIncrementalIdentificationStatus"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static SearchEventsIncrementalIdentificationStatus? FromStringOrDefault(string value)
        {
            if (value.Equals("partially_completed"))
                return SearchEventsIncrementalIdentificationStatus.PartiallyCompleted;

            if (value.Equals("completed"))
                return SearchEventsIncrementalIdentificationStatus.Completed;

            return SearchEventsIncrementalIdentificationStatus.UnsupportedValueSdkUpgradeRequired;
        }

        /// <summary>
        /// Converts the <see cref="SearchEventsIncrementalIdentificationStatus"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(SearchEventsIncrementalIdentificationStatus value)
        {
            if (value == SearchEventsIncrementalIdentificationStatus.PartiallyCompleted)
                return "partially_completed";

            if (value == SearchEventsIncrementalIdentificationStatus.Completed)
                return "completed";

            if (value == SearchEventsIncrementalIdentificationStatus.UnsupportedValueSdkUpgradeRequired)
                throw new NotImplementedException("Cannot serialize SearchEventsIncrementalIdentificationStatus.UnsupportedValueSdkUpgradeRequired: it represents an enum value returned by the API that this version of the SDK does not support. Upgrade the SDK to a version that supports the value.");

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SearchEventsIncrementalIdentificationStatus"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class SearchEventsIncrementalIdentificationStatusJsonConverter : JsonConverter<SearchEventsIncrementalIdentificationStatus>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override SearchEventsIncrementalIdentificationStatus Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            SearchEventsIncrementalIdentificationStatus? result = rawValue == null
                ? null
                : SearchEventsIncrementalIdentificationStatusValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the SearchEventsIncrementalIdentificationStatus to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="searchEventsIncrementalIdentificationStatus"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, SearchEventsIncrementalIdentificationStatus searchEventsIncrementalIdentificationStatus, JsonSerializerOptions options)
        {
            writer.WriteStringValue(SearchEventsIncrementalIdentificationStatusValueConverter.ToJsonValue(searchEventsIncrementalIdentificationStatus).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SearchEventsIncrementalIdentificationStatus"/>
    /// </summary>
    public class SearchEventsIncrementalIdentificationStatusNullableJsonConverter : JsonConverter<SearchEventsIncrementalIdentificationStatus?>
    {
        /// <summary>
        /// Returns a SearchEventsIncrementalIdentificationStatus from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override SearchEventsIncrementalIdentificationStatus? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            SearchEventsIncrementalIdentificationStatus? result = rawValue == null
                ? null
                : SearchEventsIncrementalIdentificationStatusValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the SearchEventsIncrementalIdentificationStatus to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="searchEventsIncrementalIdentificationStatus"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, SearchEventsIncrementalIdentificationStatus? searchEventsIncrementalIdentificationStatus, JsonSerializerOptions options)
        {
            writer.WriteStringValue(searchEventsIncrementalIdentificationStatus.HasValue ? SearchEventsIncrementalIdentificationStatusValueConverter.ToJsonValue(searchEventsIncrementalIdentificationStatus.Value).ToString() : "null");
        }
    }
}
