// <auto-generated>
/* 
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Fingerprint.ServerSdk.Client;

namespace Fingerprint.ServerSdk.Model
{
    /// <summary>
    /// Defines SearchEventsSource
    /// </summary>
    public enum SearchEventsSource
    {
        /// <summary>
        /// Enum Edge for value: edge
        /// </summary>
        Edge = 1,

        /// <summary>
        /// Catch-all value used when the API returns an enum value that this version of the SDK does not recognize. Upgrade the SDK to a version that supports the value.
        /// </summary>
        UnsupportedValueSdkUpgradeRequired = -1
    }

    /// <summary>
    /// Converts <see cref="SearchEventsSource"/> to and from the JSON value
    /// </summary>
    public static class SearchEventsSourceValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="SearchEventsSource"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static SearchEventsSource FromString(string value)
        {
            if (value.Equals("edge"))
                return SearchEventsSource.Edge;

            throw new NotImplementedException($"Could not convert value to type SearchEventsSource: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="SearchEventsSource"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static SearchEventsSource? FromStringOrDefault(string value)
        {
            if (value.Equals("edge"))
                return SearchEventsSource.Edge;

            return SearchEventsSource.UnsupportedValueSdkUpgradeRequired;
        }

        /// <summary>
        /// Converts the <see cref="SearchEventsSource"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(SearchEventsSource value)
        {
            if (value == SearchEventsSource.Edge)
                return "edge";

            // Serialize the catch-all value rather than throwing, so models holding an enum value
            // this SDK version does not support can still be re-serialized. The original (unsupported)
            // value is not preserved.
            if (value == SearchEventsSource.UnsupportedValueSdkUpgradeRequired)
                return "unsupported_value_sdk_upgrade_required";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SearchEventsSource"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class SearchEventsSourceJsonConverter : JsonConverter<SearchEventsSource>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override SearchEventsSource Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            SearchEventsSource? result = rawValue == null
                ? null
                : SearchEventsSourceValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the SearchEventsSource to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="searchEventsSource"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, SearchEventsSource searchEventsSource, JsonSerializerOptions options)
        {
            writer.WriteStringValue(SearchEventsSourceValueConverter.ToJsonValue(searchEventsSource).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SearchEventsSource"/>
    /// </summary>
    public class SearchEventsSourceNullableJsonConverter : JsonConverter<SearchEventsSource?>
    {
        /// <summary>
        /// Returns a SearchEventsSource from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override SearchEventsSource? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            SearchEventsSource? result = rawValue == null
                ? null
                : SearchEventsSourceValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the SearchEventsSource to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="searchEventsSource"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, SearchEventsSource? searchEventsSource, JsonSerializerOptions options)
        {
            writer.WriteStringValue(searchEventsSource.HasValue ? SearchEventsSourceValueConverter.ToJsonValue(searchEventsSource.Value).ToString() : "null");
        }
    }
}
