// <auto-generated>
/* 
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Fingerprint.ServerSdk.Client;

namespace Fingerprint.ServerSdk.Model
{
    /// <summary>
    /// Confidence level of the tampering detection. If a proxy is not detected, confidence is \"high\". If it's detected, can be \"low\", \"medium\", or \"high\". 
    /// </summary>
    /// <value>Confidence level of the tampering detection. If a proxy is not detected, confidence is \"high\". If it's detected, can be \"low\", \"medium\", or \"high\". </value>
    public enum TamperingConfidence
    {
        /// <summary>
        /// Enum Low for value: low
        /// </summary>
        Low = 1,

        /// <summary>
        /// Enum Medium for value: medium
        /// </summary>
        Medium = 2,

        /// <summary>
        /// Enum High for value: high
        /// </summary>
        High = 3
    }

    /// <summary>
    /// Converts <see cref="TamperingConfidence"/> to and from the JSON value
    /// </summary>
    public static class TamperingConfidenceValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="TamperingConfidence"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static TamperingConfidence FromString(string value)
        {
            if (value.Equals("low"))
                return TamperingConfidence.Low;

            if (value.Equals("medium"))
                return TamperingConfidence.Medium;

            if (value.Equals("high"))
                return TamperingConfidence.High;

            throw new NotImplementedException($"Could not convert value to type TamperingConfidence: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="TamperingConfidence"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static TamperingConfidence? FromStringOrDefault(string value)
        {
            if (value.Equals("low"))
                return TamperingConfidence.Low;

            if (value.Equals("medium"))
                return TamperingConfidence.Medium;

            if (value.Equals("high"))
                return TamperingConfidence.High;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="TamperingConfidence"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(TamperingConfidence value)
        {
            if (value == TamperingConfidence.Low)
                return "low";

            if (value == TamperingConfidence.Medium)
                return "medium";

            if (value == TamperingConfidence.High)
                return "high";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="TamperingConfidence"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class TamperingConfidenceJsonConverter : JsonConverter<TamperingConfidence>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override TamperingConfidence Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            TamperingConfidence? result = rawValue == null
                ? null
                : TamperingConfidenceValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the TamperingConfidence to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="tamperingConfidence"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, TamperingConfidence tamperingConfidence, JsonSerializerOptions options)
        {
            writer.WriteStringValue(TamperingConfidenceValueConverter.ToJsonValue(tamperingConfidence).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="TamperingConfidence"/>
    /// </summary>
    public class TamperingConfidenceNullableJsonConverter : JsonConverter<TamperingConfidence?>
    {
        /// <summary>
        /// Returns a TamperingConfidence from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override TamperingConfidence? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            TamperingConfidence? result = rawValue == null
                ? null
                : TamperingConfidenceValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the TamperingConfidence to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="tamperingConfidence"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, TamperingConfidence? tamperingConfidence, JsonSerializerOptions options)
        {
            writer.WriteStringValue(tamperingConfidence.HasValue ? TamperingConfidenceValueConverter.ToJsonValue(tamperingConfidence.Value).ToString() : "null");
        }
    }
}
