/*
 * Server API
 *
 * Fingerprint (https://fingerprint.com) is a device intelligence platform offering industry-leading accuracy. Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Text.Json;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using Fingerprint.ServerSdk.Api;
using Fingerprint.ServerSdk.Client;
using Fingerprint.ServerSdk.Model;


namespace Fingerprint.ServerSdk.Test.Api
{
    /// <summary>
    ///  Class for testing FingerprintApi
    /// </summary>
    public sealed class FingerprintApiTests : ApiTestsBase
    {
        private readonly IFingerprintApi _instance;

        public FingerprintApiTests() : base(Array.Empty<string>())
        {
            _instance = Host.Services.GetRequiredService<IFingerprintApi>();
        }

        /// <summary>
        /// Test DeleteVisitorData
        /// </summary>
        [Fact]
        public async Task DeleteVisitorDataAsyncTest()
        {
            const string visitorId = "AcxioeQKffpXF8iGQK3P";

            var response = await _instance.DeleteVisitorDataAsync(visitorId);
            Assert.Multiple(() =>
            {
                Assert.Single(Requests);
                Assert.Equal(HttpStatusCode.OK, response.StatusCode);

                var request = Requests.First().Request;
                Assert.Equal($"fingerprint-dotnet-sdk/{ClientUtils.ClientVersion}", request.Headers.Get("User-Agent"));
                Assert.Equal($"{ServerUrl}visitors/{visitorId}?ii=fingerprint-pro-server-api-dotnet-sdk%2f{ClientUtils.ClientVersion}", request.Url.ToString());
                Assert.Equal("DELETE", request.HttpMethod);
            });
        }

        [Fact]
        public async Task DeleteVisitorDataAsync403ErrorTest()
        {
            SetupMockResponse("errors/403_feature_not_enabled.json");
            MockResponseStatusCode = 403;

            const string visitorId = "AcxioeQKffpXF8iGQK3P";

            var response = await _instance.DeleteVisitorDataAsync(visitorId);
            Assert.Multiple(() =>
            {
                Assert.True(response.IsForbidden);
                var errorResponse = response.Forbidden();
                Assert.IsType<ErrorResponse>(errorResponse);
                Assert.Equal(ErrorCode.FeatureNotEnabled, errorResponse.Error.Code);
            });
        }

        [Fact]
        public async Task DeleteVisitorDataAsync400ErrorTest()
        {
            SetupMockResponse("errors/400_request_body_invalid.json");
            MockResponseStatusCode = 400;

            const string visitorId = "AcxioeQKffpXF8iGQK3P";

            var response = await _instance.DeleteVisitorDataAsync(visitorId);
            Assert.Multiple(() =>
            {
                Assert.True(response.IsBadRequest);
                var errorResponse = response.BadRequest();
                Assert.IsType<ErrorResponse>(errorResponse);
                Assert.Equal(ErrorCode.RequestCannotBeParsed, errorResponse.Error.Code);
            });
        }

        [Fact]
        public async Task DeleteVisitorDataAsync429ErrorTest()
        {
            SetupMockResponse("errors/429_too_many_requests.json");
            MockResponseStatusCode = 429;

            const string visitorId = "AcxioeQKffpXF8iGQK3P";

            var response = await _instance.DeleteVisitorDataAsync(visitorId);
            Assert.Multiple(() =>
            {
                Assert.True(response.IsTooManyRequests);
                var errorResponse = response.TooManyRequests();
                Assert.IsType<ErrorResponse>(errorResponse);
                Assert.Equal(ErrorCode.TooManyRequests, errorResponse.Error.Code);
            });
        }

        [Fact]
        public async Task DeleteVisitorDataAsync404ErrorTest()
        {
            SetupMockResponse("errors/404_visitor_not_found.json");
            MockResponseStatusCode = 404;

            const string visitorId = "AcxioeQKffpXF8iGQK3P";

            var response = await _instance.DeleteVisitorDataAsync(visitorId);
            Assert.Multiple(() =>
            {
                Assert.True(response.IsNotFound);
                var errorResponse = response.NotFound();
                Assert.IsType<ErrorResponse>(errorResponse);
                Assert.Equal(ErrorCode.VisitorNotFound, errorResponse.Error.Code);
            });
        }

        /// <summary>
        /// Test GetEvent
        /// </summary>
        [Fact]
        public async Task GetEventAsyncTest()
        {
            SetupMockResponse("events/get_event_200.json");

            const string eventId = "1708102555327.NLOjmg";
            var response = await _instance.GetEventAsync(eventId);

            Assert.Multiple(() =>
            {
                Assert.Single(Requests);
                Assert.Equal(HttpStatusCode.OK, response.StatusCode);

                var request = Requests.First().Request;
                Assert.Equal($"fingerprint-dotnet-sdk/{ClientUtils.ClientVersion}", request.Headers.Get("User-Agent"));
                Assert.Equal($"{ServerUrl}events/{eventId}?ii=fingerprint-pro-server-api-dotnet-sdk%2f{ClientUtils.ClientVersion}", request.Url.ToString());
                Assert.Equal("GET", request.HttpMethod);

                var model = response.Ok();
                Assert.IsType<Event>(model);
                Assert.Equal(eventId, model.EventId);
                Assert.Equal("94.142.239.124", model.IpInfo.V4.Address);
                Assert.False(model.ClonedApp);
                Assert.Equal(0, model.FactoryResetTimestamp);
                Assert.False(model.Frida);
                Assert.False(model.Incognito);
                Assert.False(model.IpBlocklist.TorNode);
                Assert.False(model.IpBlocklist.AttackSource);
                Assert.False(model.IpBlocklist.EmailSpam);
                Assert.False(model.Jailbroken);
                Assert.False(model.PrivacySettings);
                Assert.True(model.Proxy);
                Assert.Equal(ProxyDetails.ProxyTypeEnum.Residential, model.ProxyDetails.ProxyType);
                Assert.IsType<long>(model.ProxyDetails.LastSeenAt);
                Assert.False(model.RootApps);
                Assert.False(model.Tampering);
                Assert.False(model.VirtualMachine);
                Assert.False(model.Vpn);
                Assert.False(model.ClonedApp);
                Assert.IsType<long>(model.FactoryResetTimestamp);
                var factoryResetExpectedTime = DateTime.Parse("1970-01-01T00:00:00Z", CultureInfo.InvariantCulture,
                    DateTimeStyles.AdjustToUniversal);
                Assert.Equal(new DateTimeOffset(factoryResetExpectedTime).ToUnixTimeMilliseconds(), model.FactoryResetTimestamp);
            });

        }

        [Fact]
        public async Task SearchEventsAsyncTest()
        {
            SetupMockResponse("events/search/get_event_search_200.json");

            const int limit = 1;

            var response = await _instance.SearchEventsAsync(new SearchEventsRequest().WithLimit(limit));

            Assert.Multiple(() =>
            {
                Assert.Single(Requests);
                Assert.Equal(HttpStatusCode.OK, response.StatusCode);

                var request = Requests.First().Request;
                Assert.Equal($"fingerprint-dotnet-sdk/{ClientUtils.ClientVersion}", request.Headers.Get("User-Agent"));
                Assert.Equal($"{ServerUrl}events?ii=fingerprint-pro-server-api-dotnet-sdk%2f{ClientUtils.ClientVersion}&limit={limit}", request.Url.ToString());
                Assert.Equal("GET", request.HttpMethod);

                var eventSearch = response.Ok();
                Assert.IsType<EventSearch>(eventSearch);
                Assert.Single(eventSearch.Events);
                var firstEvent = eventSearch.Events.First();

                Assert.IsType<Event>(firstEvent);
                Assert.Equal("1708102555327.NLOjmg", firstEvent.EventId);
                Assert.Equal("94.142.239.124", firstEvent.IpInfo.V4.Address);
                Assert.False(firstEvent.ClonedApp);
                Assert.False(firstEvent.Emulator);
                Assert.Equal(0, firstEvent.FactoryResetTimestamp);
                Assert.False(firstEvent.Frida);
                Assert.False(firstEvent.Incognito);
                Assert.False(firstEvent.IpBlocklist.TorNode);
                Assert.False(firstEvent.IpBlocklist.AttackSource);
                Assert.False(firstEvent.IpBlocklist.EmailSpam);
                Assert.False(firstEvent.Jailbroken);
                Assert.False(firstEvent.PrivacySettings);
                Assert.True(firstEvent.Proxy);
                Assert.Equal(ProxyDetails.ProxyTypeEnum.Residential, firstEvent.ProxyDetails.ProxyType);
                Assert.IsType<long>(firstEvent.ProxyDetails.LastSeenAt);
                Assert.False(firstEvent.RootApps);
                Assert.False(firstEvent.Tampering);
                Assert.False(firstEvent.VirtualMachine);
                Assert.False(firstEvent.Vpn);
                Assert.False(firstEvent.ClonedApp);
                Assert.IsType<long>(firstEvent.FactoryResetTimestamp);
                var factoryResetExpectedTime = DateTime.Parse("1970-01-01T00:00:00Z", CultureInfo.InvariantCulture,
                    DateTimeStyles.AdjustToUniversal);
                Assert.Equal(new DateTimeOffset(factoryResetExpectedTime).ToUnixTimeMilliseconds(), firstEvent.FactoryResetTimestamp);
            });
        }

        /// <summary>
        /// Test SearchEvents
        /// </summary>
        [Fact]
        public async Task SearchEventsAsyncParamsTest()
        {
            SetupMockResponse("events/search/get_event_search_200.json");

            const int limit = 1;
            const string paginationKey = "pagination";
            const string visitorId = "AcxioeQKffpXF8iGQK3P";
            const SearchEventsBot bot = SearchEventsBot.Good;
            const string ipAddress = "10.0.0.0/24";
            const string asn = "asn";
            const string linkedId = "some_linked_id";
            const string url = "https://www.example.com/login?hope{this{works[!";
            const string origin = "com.foo.bar";
            const long start = 1582299576511;
            const long end = 1582299576513;
            const bool reverse = true;
            const bool suspect = false;
            const bool vpn = true;
            const bool virtualMachine = false;
            const bool tampering = false;
            const bool antiDetectBrowser = false;
            const bool incognito = false;
            const bool privacySettings = false;
            const bool jailbroken = false;
            const bool frida = false;
            const bool factoryReset = false;
            const bool clonedApp = false;
            const bool emulator = false;
            const bool rootApps = false;
            const SearchEventsVpnConfidence vpnConfidence = SearchEventsVpnConfidence.High;
            const float minSuspectScore = .7f;
            const bool developerTools = true;
            const bool locationSpoofing = true;
            const bool mitmAttack = true;
            const bool proxy = true;
            const string sdkVersion = "testSdkVersion";
            const SearchEventsSdkPlatform sdkPlatform = SearchEventsSdkPlatform.Js;
            var environment = new List<string> { "env1", "env2" };
            const string proximityId = "testProximityId";
            const long totalHits = 1;
            const bool torNode = false;

            var expectedUrl = $"{ServerUrl}events?"
                + $"ii=fingerprint-pro-server-api-dotnet-sdk%2f{ClientUtils.ClientVersion}"
                + $"&limit={limit}"
                + $"&pagination_key={paginationKey}"
                + $"&visitor_id={visitorId}"
                + $"&bot={SearchEventsBotValueConverter.ToJsonValue(bot)}"
                + $"&ip_address={System.Web.HttpUtility.UrlEncode(ipAddress)}"
                + $"&asn={asn}"
                + $"&linked_id={linkedId}"
                + $"&url=https%3a%2f%2fwww.example.com%2flogin%3fhope{{this{{works%5b!"
                + $"&origin={origin}"
                + $"&start={start}"
                + $"&end={end}"
                + $"&reverse={reverse.ToString().ToLower()}"
                + $"&suspect={suspect.ToString().ToLower()}"
                + $"&vpn={vpn.ToString().ToLower()}"
                + $"&virtual_machine={virtualMachine.ToString().ToLower()}"
                + $"&tampering={tampering.ToString().ToLower()}"
                + $"&anti_detect_browser={antiDetectBrowser.ToString().ToLower()}"
                + $"&incognito={incognito.ToString().ToLower()}"
                + $"&privacy_settings={privacySettings.ToString().ToLower()}"
                + $"&jailbroken={jailbroken.ToString().ToLower()}"
                + $"&frida={frida.ToString().ToLower()}"
                + $"&factory_reset={factoryReset.ToString().ToLower()}"
                + $"&cloned_app={clonedApp.ToString().ToLower()}"
                + $"&emulator={emulator.ToString().ToLower()}"
                + $"&root_apps={rootApps.ToString().ToLower()}"
                + $"&vpn_confidence={SearchEventsVpnConfidenceValueConverter.ToJsonValue(vpnConfidence)}"
                + $"&min_suspect_score={minSuspectScore.ToString(CultureInfo.InvariantCulture)}"
                + $"&developer_tools={developerTools.ToString().ToLower()}"
                + $"&location_spoofing={locationSpoofing.ToString().ToLower()}"
                + $"&mitm_attack={mitmAttack.ToString().ToLower()}"
                + $"&proxy={proxy.ToString().ToLower()}"
                + $"&sdk_version={sdkVersion}"
                + $"&sdk_platform={SearchEventsSdkPlatformValueConverter.ToJsonValue(sdkPlatform)}"
                + $"&environment[]={environment[0]}"
                + $"&environment[]={environment[1]}"
                + $"&proximity_id={proximityId}"
                + $"&total_hits={totalHits}"
                + $"&tor_node={torNode.ToString().ToLower()}";

            var response = await _instance.SearchEventsAsync(new SearchEventsRequest()
                .WithLimit(limit)
                .WithPaginationKey(paginationKey)
                .WithVisitorId(visitorId)
                .WithBot(bot)
                .WithIpAddress(ipAddress)
                .WithAsn(asn)
                .WithLinkedId(linkedId)
                .WithUrl(url)
                .WithOrigin(origin)
                .WithStart(start)
                .WithEnd(end)
                .WithReverse(reverse)
                .WithSuspect(suspect)
                .WithVpn(vpn)
                .WithVirtualMachine(virtualMachine)
                .WithTampering(tampering)
                .WithAntiDetectBrowser(antiDetectBrowser)
                .WithIncognito(incognito)
                .WithPrivacySettings(privacySettings)
                .WithJailbroken(jailbroken)
                .WithFrida(frida)
                .WithFactoryReset(factoryReset)
                .WithClonedApp(clonedApp)
                .WithEmulator(emulator)
                .WithRootApps(rootApps)
                .WithVpnConfidence(vpnConfidence)
                .WithMinSuspectScore(minSuspectScore)
                .WithDeveloperTools(developerTools)
                .WithLocationSpoofing(locationSpoofing)
                .WithMitmAttack(mitmAttack)
                .WithProxy(proxy)
                .WithSdkVersion(sdkVersion)
                .WithSdkPlatform(sdkPlatform)
                .WithEnvironment(environment)
                .WithProximityId(proximityId)
                .WithTotalHits(totalHits)
                .WithTorNode(torNode));

            Assert.Multiple(() =>
            {
                Assert.Single(Requests);
                Assert.Equal(HttpStatusCode.OK, response.StatusCode);

                var request = Requests.First().Request;
                Assert.Equal($"fingerprint-dotnet-sdk/{ClientUtils.ClientVersion}", request.Headers.Get("User-Agent"));

                Assert.Equal(expectedUrl, request.Url.ToString());
                Assert.Equal("GET", request.HttpMethod);

                var eventSearch = response.Ok();
                Assert.IsType<EventSearch>(eventSearch);
                Assert.Single(eventSearch.Events);
                var firstEvent = eventSearch.Events.First();

                Assert.IsType<Event>(firstEvent);
                Assert.Equal("1708102555327.NLOjmg", firstEvent.EventId);
                Assert.Equal("94.142.239.124", firstEvent.IpInfo.V4.Address);
                Assert.False(firstEvent.ClonedApp);
                Assert.False(firstEvent.Emulator);
                Assert.Equal(0, firstEvent.FactoryResetTimestamp);
                Assert.False(firstEvent.Frida);
                Assert.False(firstEvent.Incognito);
                Assert.False(firstEvent.IpBlocklist.TorNode);
                Assert.False(firstEvent.IpBlocklist.AttackSource);
                Assert.False(firstEvent.IpBlocklist.EmailSpam);
                Assert.False(firstEvent.Jailbroken);
                Assert.False(firstEvent.PrivacySettings);
                Assert.True(firstEvent.Proxy);
                Assert.Equal(ProxyDetails.ProxyTypeEnum.Residential, firstEvent.ProxyDetails.ProxyType);
                Assert.IsType<long>(firstEvent.ProxyDetails.LastSeenAt);
                Assert.False(firstEvent.RootApps);
                Assert.False(firstEvent.Tampering);
                Assert.False(firstEvent.VirtualMachine);
                Assert.False(firstEvent.Vpn);
                Assert.False(firstEvent.ClonedApp);
                Assert.IsType<long>(firstEvent.FactoryResetTimestamp);
                var factoryResetExpectedTime = DateTime.Parse("1970-01-01T00:00:00Z", CultureInfo.InvariantCulture,
                    DateTimeStyles.AdjustToUniversal);
                Assert.Equal(new DateTimeOffset(factoryResetExpectedTime).ToUnixTimeMilliseconds(), firstEvent.FactoryResetTimestamp);
            });
        }

        [Fact]
        public async Task SearchEventsAsync400ErrorTest()
        {
            SetupMockResponse("errors/400_request_body_invalid.json");
            MockResponseStatusCode = 400;

            const int limit = 1;
            const string ipAddress = "01234";

            var response = await _instance.SearchEventsAsync(new SearchEventsRequest()
                .WithLimit(limit)
                .WithIpAddress(ipAddress));
            Assert.Multiple(() =>
            {
                Assert.True(response.IsBadRequest);
                var errorResponse = response.BadRequest();
                Assert.IsType<ErrorResponse>(errorResponse);
                Assert.Equal(ErrorCode.RequestCannotBeParsed, errorResponse.Error.Code);
            });
        }

        [Fact]
        public async Task SearchEventsAsync403ErrorTest()
        {
            SetupMockResponse("errors/403_feature_not_enabled.json");
            MockResponseStatusCode = 403;

            const int limit = 1;

            var response = await _instance.SearchEventsAsync(new SearchEventsRequest().WithLimit(limit));
            Assert.Multiple(() =>
            {
                Assert.True(response.IsForbidden);
                var errorResponse = response.Forbidden();
                Assert.IsType<ErrorResponse>(errorResponse);
                Assert.Equal(ErrorCode.FeatureNotEnabled, errorResponse.Error.Code);
            });
        }

        /// <summary>
        /// Test UpdateEvent
        /// </summary>
        [Fact]
        public async Task UpdateEventAsyncTest()
        {
            const string eventId = "1708102555327.NLOjmg";
            var eventUpdate = new EventUpdate
            {
                Suspect = false,
                LinkedId = "new_linked_id",
                Tags = new Dictionary<string, object>
                {
                    { "foo", "bar" },
                    { "baz", true }
                }
            };

            var response = await _instance.UpdateEventAsync(eventId, eventUpdate);
            Assert.Multiple(() =>
            {
                Assert.Single(Requests);
                Assert.Equal(HttpStatusCode.OK, response.StatusCode);

                var firstRequest = Requests.First();
                var request = firstRequest.Request;
                var body = firstRequest.Body;

                Assert.Equal($"fingerprint-dotnet-sdk/{ClientUtils.ClientVersion}", request.Headers.Get("User-Agent"));
                Assert.Equal($"{ServerUrl}events/{eventId}?ii=fingerprint-pro-server-api-dotnet-sdk%2f{ClientUtils.ClientVersion}", request.Url.ToString());
                Assert.Equal("PATCH", request.HttpMethod);
                Assert.Equal("application/json", request.ContentType);
                Assert.Equal(JsonSerializer.Serialize(eventUpdate, Host.Services.GetService<JsonSerializerOptions>()), body);
            });
        }

        /// <summary>
        /// </summary>
        [Fact]
        public async Task UpdateEventAsync400ErrorTest()
        {
            SetupMockResponse("errors/400_request_body_invalid.json");
            MockResponseStatusCode = 400;

            const string eventId = "1708102555327.NLOjmg";
            var eventUpdate = new EventUpdate
            {
                Suspect = false,
                LinkedId = "new_linked_id",
                Tags = new Dictionary<string, object>
                {
                    { "foo", "bar" },
                    { "baz", true }
                }
            };

            var response = await _instance.UpdateEventAsync(eventId, eventUpdate);
            Assert.Multiple(() =>
            {
                Assert.True(response.IsBadRequest);
                var errorResponse = response.BadRequest();
                Assert.IsType<ErrorResponse>(errorResponse);
                Assert.Equal(ErrorCode.RequestCannotBeParsed, errorResponse.Error.Code);
            });
        }

        /// <summary>
        /// </summary>
        [Fact]
        public async Task UpdateEventAsync403ErrorTest()
        {
            SetupMockResponse("errors/403_feature_not_enabled.json");
            MockResponseStatusCode = 403;

            const string eventId = "1708102555327.NLOjmg";
            var eventUpdate = new EventUpdate
            {
                Suspect = false,
                LinkedId = "new_linked_id",
                Tags = new Dictionary<string, object>
                {
                    { "foo", "bar" },
                    { "baz", true }
                }
            };

            var response = await _instance.UpdateEventAsync(eventId, eventUpdate);
            Assert.Multiple(() =>
            {
                Assert.True(response.IsForbidden);
                var errorResponse = response.Forbidden();
                Assert.IsType<ErrorResponse>(errorResponse);
                Assert.Equal(ErrorCode.FeatureNotEnabled, errorResponse.Error.Code);
            });
        }

        /// <summary>
        /// </summary>
        [Fact]
        public async Task UpdateEventAsync404ErrorTest()
        {
            SetupMockResponse("errors/404_event_not_found.json");
            MockResponseStatusCode = 404;

            const string eventId = "1708102555327.NLOjmg";
            var eventUpdate = new EventUpdate
            {
                Suspect = false,
                LinkedId = "new_linked_id",
                Tags = new Dictionary<string, object>
                {
                    { "foo", "bar" },
                    { "baz", true }
                }
            };

            var response = await _instance.UpdateEventAsync(eventId, eventUpdate);
            Assert.Multiple(() =>
            {
                Assert.True(response.IsNotFound);
                var errorResponse = response.NotFound();
                Assert.IsType<ErrorResponse>(errorResponse);
                Assert.Equal(ErrorCode.EventNotFound, errorResponse.Error.Code);
            });
        }

        /// <summary>
        /// </summary>
        [Fact]
        public async Task UpdateEventAsync409ErrorTest()
        {
            SetupMockResponse("errors/409_state_not_ready.json");
            MockResponseStatusCode = 409;

            const string eventId = "1708102555327.NLOjmg";
            var eventUpdate = new EventUpdate
            {
                Suspect = false,
                LinkedId = "new_linked_id",
                Tags = new Dictionary<string, object>
                {
                    { "foo", "bar" },
                    { "baz", true }
                }
            };

            var response = await _instance.UpdateEventAsync(eventId, eventUpdate);
            Assert.Multiple(() =>
            {
                Assert.True(response.IsConflict);
                var errorResponse = response.Conflict();
                Assert.IsType<ErrorResponse>(errorResponse);
                Assert.Equal(ErrorCode.StateNotReady, errorResponse.Error.Code);
            });
        }
    }
}