/*
 * Server API
 *
 * Fingerprint (https://fingerprint.com) is a device intelligence platform offering industry-leading accuracy. Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Text.Json;
using Xunit;
using Fingerprint.ServerSdk.Client;
using Fingerprint.ServerSdk.Model;
using System.Text.Json.Serialization;

namespace Fingerprint.ServerSdk.Test.Api
{
    public class SearchEventsParameterSerializationTests
    {

        public class Wrapper
        {
            [JsonPropertyName("start")]
            public SearchEventsStartParameter Start { get; set; }

            [JsonPropertyName("end")]
            public SearchEventsEndParameter End { get; set; }
        }

        private static JsonSerializerOptions CreateOptions()
        {
            var options = new JsonSerializerOptions();
            options.Converters.Add(new DateTimeJsonConverter());
            options.Converters.Add(new SearchEventsStartParameterJsonConverter());
            options.Converters.Add(new SearchEventsEndParameterJsonConverter());
            return options;
        }

        [Fact]
        public void SearchEventsStartParameter_Long_RoundTrips()
        {
            var options = CreateOptions();
            var today = DateTime.Today;

            var wrapper = new Wrapper
            {
                Start = new SearchEventsStartParameter(1767225600000L),
                End = new SearchEventsEndParameter(today)
            };
            var json = JsonSerializer.Serialize(wrapper, options);
            var deserialized = JsonSerializer.Deserialize<Wrapper>(json, options);

            Assert.NotNull(deserialized);
            Assert.Equal(1767225600000L, deserialized.Start.Long);
            Assert.Null(deserialized.Start.DateTime);
            Assert.NotNull(deserialized.End.DateTime);
            Assert.Null(deserialized.End.Long);
        }
    }
}
