// <auto-generated>
/* 
 * Fingerprint Server API
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */using System;
using System.Linq;
using System.Collections.Generic;
using Fingerprint.ServerSdk.Client;

namespace Fingerprint.ServerSdk
{
    /// <summary>
    /// A class which will provide tokens.
    /// </summary>
    public abstract class TokenProvider<TTokenBase> where TTokenBase : TokenBase
    {
        /// <summary>
        /// Gets a token asynchronously for the specified header.
        /// </summary>
        /// <param name="header">The header name to retrieve a token for. Empty string for non-API-key authentication schemes.</param>
        /// <param name="cancellation">Cancellation token for the asynchronous operation.</param>
        /// <returns>A task that returns the requested token.</returns>
        protected internal abstract System.Threading.Tasks.ValueTask<TTokenBase> GetAsync(string header = "", System.Threading.CancellationToken cancellation = default);
    }
}